WITH dr as (
	SELECT '01' as "CODE", 'SILLON RHODANIEN' as "DR_25", 'Sud' as "DIR_8" FROM DUAL UNION ALL
	SELECT '02' as "CODE", 'PICARDIE' as "DR_25", 'Nord Est' as "DIR_8" FROM DUAL UNION ALL
	SELECT '03' as "CODE", 'AUVERGNE' as "DR_25", 'Sud' as "DIR_8" FROM DUAL UNION ALL
	SELECT '04' as "CODE", 'PROVENCE-ALPES DU SUD' as "DR_25", 'Sud' as "DIR_8" FROM DUAL UNION ALL
	SELECT '05' as "CODE", 'PROVENCE-ALPES DU SUD' as "DR_25", 'Sud' as "DIR_8" FROM DUAL UNION ALL
	SELECT '06' as "CODE", 'COTE D''AZUR' as "DR_25", 'Sud' as "DIR_8" FROM DUAL UNION ALL
	SELECT '07' as "CODE", 'SILLON RHODANIEN' as "DR_25", 'Sud' as "DIR_8" FROM DUAL UNION ALL
	SELECT '08' as "CODE", 'CHAMPAGNE ARDENNE' as "DR_25", 'Nord Est' as "DIR_8" FROM DUAL UNION ALL
	SELECT '09' as "CODE", 'MIDI PYRENEES SUD' as "DR_25", 'Sud' as "DIR_8" FROM DUAL UNION ALL
	SELECT '10' as "CODE", 'CHAMPAGNE ARDENNE' as "DR_25", 'Nord Est' as "DIR_8" FROM DUAL UNION ALL
	SELECT '11' as "CODE", 'LANGUEDOC-ROUSSILLON' as "DR_25", 'Sud' as "DIR_8" FROM DUAL UNION ALL
	SELECT '12' as "CODE", 'NORD MIDI-PYRENEES' as "DR_25", 'Sud' as "DIR_8" FROM DUAL UNION ALL
	SELECT '13' as "CODE", 'PROVENCE-ALPES DU SUD' as "DR_25", 'Sud' as "DIR_8" FROM DUAL UNION ALL
	SELECT '14' as "CODE", 'NORMANDIE' as "DR_25", 'Nord Est' as "DIR_8" FROM DUAL UNION ALL
	SELECT '15' as "CODE", 'AUVERGNE' as "DR_25", 'Sud' as "DIR_8" FROM DUAL UNION ALL
	SELECT '16' as "CODE", 'POITOU-CHARENTES' as "DR_25", 'Ouest' as "DIR_8" FROM DUAL UNION ALL
	SELECT '17' as "CODE", 'POITOU-CHARENTES' as "DR_25", 'Ouest' as "DIR_8" FROM DUAL UNION ALL
	SELECT '18' as "CODE", 'CENTRE-VAL DE LOIRE' as "DR_25", 'Ouest' as "DIR_8" FROM DUAL UNION ALL
	SELECT '19' as "CODE", 'LIMOUSIN' as "DR_25", 'Ouest' as "DIR_8" FROM DUAL UNION ALL
	SELECT '21' as "CODE", 'BOURGOGNE' as "DR_25", 'Nord Est' as "DIR_8" FROM DUAL UNION ALL
	SELECT '22' as "CODE", 'BRETAGNE' as "DR_25", 'Ouest' as "DIR_8" FROM DUAL UNION ALL
	SELECT '23' as "CODE", 'LIMOUSIN' as "DR_25", 'Ouest' as "DIR_8" FROM DUAL UNION ALL
	SELECT '24' as "CODE", 'AQUITAINE NORD' as "DR_25", 'Ouest' as "DIR_8" FROM DUAL UNION ALL
	SELECT '25' as "CODE", 'ALSACE FRANCHE-COMTE' as "DR_25", 'Nord Est' as "DIR_8" FROM DUAL UNION ALL
	SELECT '26' as "CODE", 'SILLON RHODANIEN' as "DR_25", 'Sud' as "DIR_8" FROM DUAL UNION ALL
	SELECT '27' as "CODE", 'NORMANDIE' as "DR_25", 'Nord Est' as "DIR_8" FROM DUAL UNION ALL
	SELECT '28' as "CODE", 'CENTRE-VAL DE LOIRE' as "DR_25", 'Ouest' as "DIR_8" FROM DUAL UNION ALL
	SELECT '29' as "CODE", 'BRETAGNE' as "DR_25", 'Ouest' as "DIR_8" FROM DUAL UNION ALL
	SELECT '30' as "CODE", 'LANGUEDOC-ROUSSILLON' as "DR_25", 'Sud' as "DIR_8" FROM DUAL UNION ALL
	SELECT '31' as "CODE", 'MIDI PYRENEES SUD' as "DR_25", 'Sud' as "DIR_8" FROM DUAL UNION ALL
	SELECT '32' as "CODE", 'MIDI PYRENEES SUD' as "DR_25", 'Sud' as "DIR_8" FROM DUAL UNION ALL
	SELECT '33' as "CODE", 'AQUITAINE NORD' as "DR_25", 'Ouest' as "DIR_8" FROM DUAL UNION ALL
	SELECT '34' as "CODE", 'LANGUEDOC-ROUSSILLON' as "DR_25", 'Sud' as "DIR_8" FROM DUAL UNION ALL
	SELECT '35' as "CODE", 'BRETAGNE' as "DR_25", 'Ouest' as "DIR_8" FROM DUAL UNION ALL
	SELECT '36' as "CODE", 'CENTRE-VAL DE LOIRE' as "DR_25", 'Ouest' as "DIR_8" FROM DUAL UNION ALL
	SELECT '37' as "CODE", 'CENTRE-VAL DE LOIRE' as "DR_25", 'Ouest' as "DIR_8" FROM DUAL UNION ALL
	SELECT '38' as "CODE", 'ALPES' as "DR_25", 'Sud' as "DIR_8" FROM DUAL UNION ALL
	SELECT '39' as "CODE", 'ALSACE FRANCHE-COMTE' as "DR_25", 'Nord Est' as "DIR_8" FROM DUAL UNION ALL
	SELECT '40' as "CODE", 'PYRENEES ET LANDES' as "DR_25", 'Ouest' as "DIR_8" FROM DUAL UNION ALL
	SELECT '41' as "CODE", 'CENTRE-VAL DE LOIRE' as "DR_25", 'Ouest' as "DIR_8" FROM DUAL UNION ALL
	SELECT '42' as "CODE", 'SILLON RHODANIEN' as "DR_25", 'Sud' as "DIR_8" FROM DUAL UNION ALL
	SELECT '43' as "CODE", 'AUVERGNE' as "DR_25", 'Sud' as "DIR_8" FROM DUAL UNION ALL
	SELECT '44' as "CODE", 'PAYS DE LA LOIRE' as "DR_25", 'Ouest' as "DIR_8" FROM DUAL UNION ALL
	SELECT '45' as "CODE", 'CENTRE-VAL DE LOIRE' as "DR_25", 'Ouest' as "DIR_8" FROM DUAL UNION ALL
	SELECT '46' as "CODE", 'NORD MIDI-PYRENEES' as "DR_25", 'Sud' as "DIR_8" FROM DUAL UNION ALL
	SELECT '47' as "CODE", 'AQUITAINE NORD' as "DR_25", 'Ouest' as "DIR_8" FROM DUAL UNION ALL
	SELECT '48' as "CODE", 'NORD MIDI-PYRENEES' as "DR_25", 'Sud' as "DIR_8" FROM DUAL UNION ALL
	SELECT '49' as "CODE", 'PAYS DE LA LOIRE' as "DR_25", 'Ouest' as "DIR_8" FROM DUAL UNION ALL
	SELECT '50' as "CODE", 'NORMANDIE' as "DR_25", 'Nord Est' as "DIR_8" FROM DUAL UNION ALL
	SELECT '51' as "CODE", 'CHAMPAGNE ARDENNE' as "DR_25", 'Nord Est' as "DIR_8" FROM DUAL UNION ALL
	SELECT '52' as "CODE", 'CHAMPAGNE ARDENNE' as "DR_25", 'Nord Est' as "DIR_8" FROM DUAL UNION ALL
	SELECT '53' as "CODE", 'PAYS DE LA LOIRE' as "DR_25", 'Ouest' as "DIR_8" FROM DUAL UNION ALL
	SELECT '54' as "CODE", 'LORRAINE' as "DR_25", 'Nord Est' as "DIR_8" FROM DUAL UNION ALL
	SELECT '55' as "CODE", 'LORRAINE' as "DR_25", 'Nord Est' as "DIR_8" FROM DUAL UNION ALL
	SELECT '56' as "CODE", 'BRETAGNE' as "DR_25", 'Ouest' as "DIR_8" FROM DUAL UNION ALL
	SELECT '57' as "CODE", 'LORRAINE' as "DR_25", 'Nord Est' as "DIR_8" FROM DUAL UNION ALL
	SELECT '58' as "CODE", 'BOURGOGNE' as "DR_25", 'Nord Est' as "DIR_8" FROM DUAL UNION ALL
	SELECT '59' as "CODE", 'NORD PAS DE CALAIS' as "DR_25", 'Nord Est' as "DIR_8" FROM DUAL UNION ALL
	SELECT '60' as "CODE", 'PICARDIE' as "DR_25", 'Nord Est' as "DIR_8" FROM DUAL UNION ALL
	SELECT '61' as "CODE", 'NORMANDIE' as "DR_25", 'Nord Est' as "DIR_8" FROM DUAL UNION ALL
	SELECT '62' as "CODE", 'NORD PAS DE CALAIS' as "DR_25", 'Nord Est' as "DIR_8" FROM DUAL UNION ALL
	SELECT '63' as "CODE", 'AUVERGNE' as "DR_25", 'Sud' as "DIR_8" FROM DUAL UNION ALL
	SELECT '64' as "CODE", 'PYRENEES ET LANDES' as "DR_25", 'Ouest' as "DIR_8" FROM DUAL UNION ALL
	SELECT '65' as "CODE", 'PYRENEES ET LANDES' as "DR_25", 'Ouest' as "DIR_8" FROM DUAL UNION ALL
	SELECT '66' as "CODE", 'LANGUEDOC-ROUSSILLON' as "DR_25", 'Sud' as "DIR_8" FROM DUAL UNION ALL
	SELECT '67' as "CODE", 'ALSACE FRANCHE-COMTE' as "DR_25", 'Nord Est' as "DIR_8" FROM DUAL UNION ALL
	SELECT '68' as "CODE", 'ALSACE FRANCHE-COMTE' as "DR_25", 'Nord Est' as "DIR_8" FROM DUAL UNION ALL
	SELECT '69' as "CODE", 'SILLON RHODANIEN' as "DR_25", 'Sud' as "DIR_8" FROM DUAL UNION ALL
	SELECT '70' as "CODE", 'ALSACE FRANCHE-COMTE' as "DR_25", 'Nord Est' as "DIR_8" FROM DUAL UNION ALL
	SELECT '71' as "CODE", 'BOURGOGNE' as "DR_25", 'Nord Est' as "DIR_8" FROM DUAL UNION ALL
	SELECT '72' as "CODE", 'PAYS DE LA LOIRE' as "DR_25", 'Ouest' as "DIR_8" FROM DUAL UNION ALL
	SELECT '73' as "CODE", 'ALPES' as "DR_25", 'Sud' as "DIR_8" FROM DUAL UNION ALL
	SELECT '74' as "CODE", 'ALPES' as "DR_25", 'Sud' as "DIR_8" FROM DUAL UNION ALL
	SELECT '75' as "CODE", 'PARIS' as "DR_25", 'Ile De France' as "DIR_8" FROM DUAL UNION ALL
	SELECT '76' as "CODE", 'NORMANDIE' as "DR_25", 'Nord Est' as "DIR_8" FROM DUAL UNION ALL
	SELECT '77' as "CODE", 'ILE DE France EST' as "DR_25", 'Ile De France' as "DIR_8" FROM DUAL UNION ALL
	SELECT '78' as "CODE", 'ILE DE France OUEST' as "DR_25", 'Ile De France' as "DIR_8" FROM DUAL UNION ALL
	SELECT '79' as "CODE", 'POITOU-CHARENTES' as "DR_25", 'Ouest' as "DIR_8" FROM DUAL UNION ALL
	SELECT '80' as "CODE", 'PICARDIE' as "DR_25", 'Nord Est' as "DIR_8" FROM DUAL UNION ALL
	SELECT '81' as "CODE", 'NORD MIDI-PYRENEES' as "DR_25", 'Sud' as "DIR_8" FROM DUAL UNION ALL
	SELECT '82' as "CODE", 'NORD MIDI-PYRENEES' as "DR_25", 'Sud' as "DIR_8" FROM DUAL UNION ALL
	SELECT '83' as "CODE", 'COTE D''AZUR' as "DR_25", 'Sud' as "DIR_8" FROM DUAL UNION ALL
	SELECT '84' as "CODE", 'PROVENCE-ALPES DU SUD' as "DR_25", 'Sud' as "DIR_8" FROM DUAL UNION ALL
	SELECT '85' as "CODE", 'PAYS DE LA LOIRE' as "DR_25", 'Ouest' as "DIR_8" FROM DUAL UNION ALL
	SELECT '86' as "CODE", 'POITOU-CHARENTES' as "DR_25", 'Ouest' as "DIR_8" FROM DUAL UNION ALL
	SELECT '87' as "CODE", 'LIMOUSIN' as "DR_25", 'Ouest' as "DIR_8" FROM DUAL UNION ALL
	SELECT '88' as "CODE", 'LORRAINE' as "DR_25", 'Nord Est' as "DIR_8" FROM DUAL UNION ALL
	SELECT '89' as "CODE", 'BOURGOGNE' as "DR_25", 'Nord Est' as "DIR_8" FROM DUAL UNION ALL
	SELECT '90' as "CODE", 'ALSACE FRANCHE-COMTE' as "DR_25", 'Nord Est' as "DIR_8" FROM DUAL UNION ALL
	SELECT '91' as "CODE", 'ILE DE France EST' as "DR_25", 'Ile De France' as "DIR_8" FROM DUAL UNION ALL
	SELECT '92' as "CODE", 'ILE DE France OUEST' as "DR_25", 'Ile De France' as "DIR_8" FROM DUAL UNION ALL
	SELECT '93' as "CODE", 'ILE DE France EST' as "DR_25", 'Ile De France' as "DIR_8" FROM DUAL UNION ALL
	SELECT '94' as "CODE", 'ILE DE France EST' as "DR_25", 'Ile De France' as "DIR_8" FROM DUAL UNION ALL
	SELECT '95' as "CODE", 'ILE DE France OUEST' as "DR_25", 'Ile De France' as "DIR_8" FROM DUAL
)

, aff_130 as
(
	SELECT DISTINCT dem.DEM_ID_PRM as POINT, dem.AFF_T_DISCO as AFFAIRE, dem.DEM_D_EFFET as DATE_EFFET
	, DENSE_RANK() OVER (PARTITION BY dem.DEM_ID_PRM ORDER BY dem.DEM_D_DEMANDE DESC) as RANG
	FROM SUIVI.DEMANDE dem
	JOIN SUIVI.NATURE nat ON dem.DEM_K_NAT = nat.NAT_ID
	WHERE 1=1
	AND nat.NAT_C_PRESTATION IN ('F130B')
	AND dem.DEM_R_STATUT IN ('AFF-ENCOURS')
)

, aff_BP as
(
	SELECT DISTINCT dem.DEM_ID_PRM as POINT, dem.AFF_T_DISCO as AFFAIRE
	, CASE WHEN nat.NAT_C_PRESTATION = 'F800B' THEN 'LONG' ELSE 'COURT' END TYPE
	, DENSE_RANK() OVER (PARTITION BY dem.DEM_ID_PRM ORDER BY dem.DEM_D_DEMANDE DESC) as RANG
	FROM SUIVI.DEMANDE dem
	JOIN SUIVI.NATURE nat ON dem.DEM_K_NAT = nat.NAT_ID
	WHERE 1=1
	AND nat.NAT_C_PRESTATION IN ('F800B', 'F820')
	AND dem.DEM_ID_PRM NOT LIKE '00%'
	AND dem.DEM_R_STATUT <> 'AFF-ANNULEE'
)

SELECT POINT
, CODE_INSEE, CODE_DEPARTEMENT, dr.DIR_8, dr.DR_25
, SI, EN_SERVICE, OH
, CALENDRIER, CAL_LIBELLE_COMPTEUR, COMPTEUR
, F130_EC, DATE_EFFET
, BP
FROM
(
	SELECT prm.PRM_ID as POINT
	, CASE WHEN prm.PRM_DG_APP_INSTANCE_SI IS NULL THEN 'D' ELSE 'G' END as SI
	, CASE WHEN prm.PRM_SC_ETAT_CONTRACTUEL_CODE = 'SERVC' THEN 'O' ELSE 'N' END EN_SERVICE
	, CASE WHEN prm.PRM_DG_NUMERO_CONTRAT = 'PROTOC-501' THEN 'O'  ELSE 'N' END as OH
	, aff_130.AFFAIRE F130_EC, aff_130.DATE_EFFET
	, aff_BP.TYPE as BP
	, situ.SCN_GF_CALENDRIER_FOURN_CODE as CALENDRIER
	, cal.CAL_LIBELLE_COMPTEUR
	, DECODE(scm.SCM_DC_STRUCTURE_COMPTAGE_CODE,
		'AMM', 'LINKY',
		scm.SCM_DC_STRUCTURE_COMPTAGE_CODE
		) as COMPTEUR
	, prm.PRM_AI_CODE_INSEE CODE_INSEE, SUBSTR(prm.PRM_AI_CODE_INSEE, 1, 2) CODE_DEPARTEMENT
	FROM SGEL_PRM_SCH.T_PRM prm
	LEFT JOIN SGEL_PRM_SCH.T_SITUATION_CONTRACTUELLE situ ON prm.SCN_ID = situ.SCN_ID
	LEFT JOIN SGEL_SCH.T_CALENDRIER cal ON situ.SCN_GF_CALENDRIER_FOURN_CODE = cal.CAL_CODE
	LEFT JOIN SGEL_PRM_SCH.T_SITUATION_COMPTAGE scm ON scm.SCM_ID = prm.SCM_ID
	LEFT JOIN aff_130 aff_130 ON (prm.PRM_ID = aff_130.POINT AND aff_130.RANG = 1)
	LEFT JOIN aff_BP aff_BP ON (prm.PRM_ID = aff_BP.POINT AND aff_BP.RANG = 1)
	WHERE 1=1
	AND prm.PRM_SC_SEGMENT IN ('C5', 'INDET')
	AND prm.PRM_ID IN @@IN1@@
	--AND prm.PRM_ID IN ('19524167854286', '01100144557179', '01100289273089')
) t
LEFT JOIN dr ON t.CODE_DEPARTEMENT = dr.CODE