CREATE TABLE "CAPC5"."@@TABLE_NAME@@" (
	"PRM" VARCHAR2(14 BYTE), 
	"AFFAIRE" VARCHAR2(8 BYTE), 
	"SI" VARCHAR2(5 BYTE), 
	"PRESTATION" VARCHAR2(5 BYTE), 
	"STATUT" VARCHAR2(12 BYTE), 
	"ETAT_EXTERNE" VARCHAR2(40 BYTE), 
	"FOURNISSEUR" VARCHAR2(50 BYTE), 
	"TYPE_OFFRE" VARCHAR2(2 BYTE), 
	"DATE_DEMANDE" VARCHAR2(20 BYTE), 
	"DATE_EFFET" VARCHAR2(20 BYTE), 
	"PS_INIT" VARCHAR2(4 BYTE), 
	"PS_CIBLE" VARCHAR2(4 BYTE), 
	"FTA_INIT" VARCHAR2(26 BYTE), 
	"FTA_CIBLE" VARCHAR2(26 BYTE), 
	"CAL_INIT" VARCHAR2(26 BYTE), 
	"CAL_CIBLE" VARCHAR2(26 BYTE), 
	"CAL_COPIE_INIT" VARCHAR2(26 BYTE), 
	"CAL_COPIE_CIBLE" VARCHAR2(26 BYTE), 
	"F130_EC_ISO" VARCHAR2(26 BYTE)
) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAPC5_DATA"