CREATE OR REPLACE FORCE VIEW "CAPC5"."@@VIEW_NAME@@" (
"PRM", "AFFAIRE", "SI", "PRESTATION", "STATUT", "ETAT_EXTERNE", "FOURNISSEUR", "TYPE_OFFRE"
, "DATE_DEMANDE", "DATE_EFFET", "PS_INIT", "PS_CIBLE", "FTA_INIT", "FTA_CIBLE", "CAL_INIT", "CAL_CIBLE"
, "CAL_COPIE_INIT", "CAL_COPIE_CIBLE", "F130_EC_ISO")
AS
SELECT "PRM","AFFAIRE","SI","PRESTATION","STATUT","ETAT_EXTERNE","FOURNISSEUR","TYPE_OFFRE"
,"DATE_DEMANDE","DATE_EFFET","PS_INIT","PS_CIBLE","FTA_INIT","FTA_CIBLE","CAL_INIT","CAL_CIBLE"
,"CAL_COPIE_INIT","CAL_COPIE_CIBLE","F130_EC_ISO"
FROM @@TABLE_NAME@@