--Recherche d'affaire infos par PDL / No. Dossier (SGE-L)
SELECT * FROM
	(SELECT DISTINCT
	prs.AFF_ID as AFFAIRE,
	PRE_DEM_ACT_DEM_LOGIN_INIT as INIT,
	PRE_ID_PRM as PDL,
	PRE_TECH_DATE_CREATION as CREATION,
	PRE_FICHEPRESTA_CODE "Presta",
	PRE_FICHEOPTION_CODE "Option",
	stai.EST_T_ETAT "Etat interne",
	stae.EST_T_ETAT "Etat externe",
	sta.EST_T_STATUT "Statut",
	prs.PRE_ETAT_CODE "Etat",
	prs.PRE_SICONTRACTUEL_CODE "SI",
	prs.PRE_DEM_ACTEURMARCHE_CODE "ACM",
	PRE_DEM_CO_IDCONTRAT "CTR",
	acm.ACM_T_LIB as "Fournisseur",
	PRE_DEM_SC_DOMTENSION_CODE "D.T",
	PRE_DEM_SC_SEGMENT_CODE "SEG",
	PRE_DEM_STANDARDREA_CODE "STDR",
	PRE_DEM_CF_CATEGORIE_CODE "CAT"
	FROM SGEL_IAP_SCH.T_PRESTATION prs
	JOIN SGEL_IAP_SCH.T_AFFAIRE aff ON prs.AFF_ID = aff.AFF_ID
	JOIN SGEL_TRV_SCH.T_TRANSCODIFICATION trvi ON aff.AFF_ETAT_INTERNE = trvi.TRA_VAL_ENTREE
	JOIN SGEL_TRV_SCH.T_TRANSCODIFICATION trve ON aff.AFF_ETAT_EXTERNE = trve.TRA_VAL_ENTREE
	JOIN SUIVI.ETAT_STATUT stai ON trvi.TRA_VAL_SORTIE = stai.EST_C_ETAT
	JOIN SUIVI.ETAT_STATUT stae ON trve.TRA_VAL_SORTIE = stae.EST_C_ETAT
	JOIN SUIVI.ETAT_STATUT sta ON trvi.TRA_VAL_SORTIE = sta.EST_C_ETAT
	JOIN CONTRAT.ACTEUR_MARCHE acm ON acm.ACM_C_CODE = prs.PRE_DEM_ACTEURMARCHE_CODE)
WHERE
PDL = '19164399414753'
--AFFAIRE = 'A01PCW3M'
--CREATION > TO_DATE('21/10/2014') AND INIT IS NOT NULL
ORDER BY CREATION DESC
;


--Avancement affaires L
SELECT
THS_CODE_AGREGAT "Affaire",
THS_LIBELLE "Champ modifié",
THS_VALEUR_INITIALE "Valeur initiale",
THS_VALEUR_CHAMP "Valeur finale",
THS_DATE "Date",
THS_UTILISATEUR "Utilisateur",
THS_TRANSACTION_ID "ID flux"
FROM SGEL_SCH.T_TRACE_HISTORIQUE trh
WHERE THS_CODE_AGREGAT = 'A01PCV4F'
ORDER BY THS_DATE
;

--Modification créneau horaire affaire L
SELECT iaf.AFF_ID, dem.INT_DEM_ID, dem.INT_DEM_C5_CRENEAU_H_CODE
                    FROM SGEL_IAP_SCH.T_INTERVENTION_AFFAIRE iaf
                    JOIN SGEL_IAP_SCH.T_INTERVENTION inter ON iaf.INT_ID = inter.INT_ID
                    JOIN SGEL_IAP_SCH.T_DEMANDE dem ON dem.INT_DEM_ID = inter.INT_DEM_ID
                    WHERE iaf.AFF_ID = 'A01PCXBV'
;

UPDATE SGEL_IAP_SCH.T_DEMANDE SET INT_DEM_C5_CRENEAU_H_CODE = 'JOU'
WHERE INT_DEM_ID IN(
                    SELECT dem.INT_DEM_ID
                    FROM SGEL_IAP_SCH.T_INTERVENTION_AFFAIRE iaf
                    JOIN SGEL_IAP_SCH.T_INTERVENTION inter ON iaf.INT_ID = inter.INT_ID
                    JOIN SGEL_IAP_SCH.T_DEMANDE dem ON dem.INT_DEM_ID = inter.INT_DEM_ID
                    WHERE iaf.AFF_ID = 'A01PCXBV'
                    )
;

--Codes libellés
SELECT *
FROM SGEL_TRV_SCH.T_REFERENTIEL
WHERE REF_CODE = 'UPIN';


--Prestation
SELECT * FROM SGEL_IAP_SCH.T_PRESTATION prs
JOIN SGEL_IAP_SCH.T_STRUCTURE_TARIFAIRE tar ON prs.PRE_DEM_STR_TAR_ID = tar.STR_TAR_ID
JOIN SGEL_IAP_SCH.T_RECEVABILITE rec ON prs.PRE_REC_ID = rec.PRE_REC_ID
WHERE prs.AFF_ID = 'A01YPK8I';
;

--Intervention
SELECT * FROM SGEL_IAP_SCH.T_INTERVENTION_AFFAIRE intaff
JOIN SGEL_IAP_SCH.T_INTERVENTION inter ON intaff.INT_ID = inter.INT_ID
JOIN SGEL_IAP_SCH.T_DEMANDE dem ON inter.INT_DEM_ID = dem.INT_DEM_ID
LEFT JOIN SGEL_IAP_SCH.T_PLANIFICATION planif ON inter.PLA_ID = planif.PLA_ID
WHERE intaff.AFF_ID = 'A01YPK8I';

--Transcos contrats
SELECT * FROM SGEL_TRV_SCH.T_TRANSCODIFICATION;

--Transcos Jalons
SELECT * FROM SGEL_TRV_SCH.T_REFERENTIEL
WHERE REF_CODE = 'FTEC'
;

--Transcos calendriers
SELECT * FROM SGEL_TRV_SCH.T_TRANSCODIFICATION
WHERE TRA_CODE = 'CADTOCAL'
ORDER BY TRA_VAL_ENTREE
;

--Jalons
SELECT * FROM SGEL_IAP_SCH.T_JALON jal
JOIN SUIVI.DEMANDE dem ON dem.DEM_ID = jal.AFF_ID_SEQUENCE
WHERE AFF_T_DISCO = 'A02X4Y1H'
;
