--Notifs par date
SELECT TO_CHAR(NFT_D_CREATION, 'YYYY/MM/DD') as DATE_VOL, COUNT(1) as VOLUMETRIE
FROM C5.NOTIF_FIN_TRT
WHERE NFT_D_CREATION >=  '01/01/2017'
GROUP BY TO_CHAR(NFT_D_CREATION, 'YYYY/MM/DD')
ORDER BY 1 DESC
;

--Nb evt long par date
SELECT TO_CHAR(EME_D_CREATION, 'YYYY/MM/DD') as DATE_VOL, COUNT(1) as VOLUMETRIE
FROM C5.EME_LG_AVA_PRS
WHERE EME_D_CREATION >=  '01/01/2017'
GROUP BY TO_CHAR(EME_D_CREATION, 'YYYY/MM/DD')
ORDER BY 1
;

--Nb evt crt par date
SELECT TO_CHAR(EME_D_CREATION, 'YYYY/MM/DD') as DATE_VOL, COUNT(1) as VOLUMETRIE
FROM C5.EME_CRT_AVA_PRS
WHERE TRUNC(EME_D_CREATION) > '01/01/17'
GROUP BY TO_CHAR(EME_D_CREATION, 'YYYY/MM/DD')
ORDER BY 1
;

--Pbox et evt pour une date donnée evt court
SELECT EME_C_CODE, EME_C_PRB, COUNT(1)
FROM C5.EME_CRT_AVA_PRS
WHERE TRUNC(EME_D_CREATION) = '05/05/17'
GROUP BY EME_C_CODE, EME_C_PRB
ORDER BY 3 DESC
;

--Pbox et evt pour une date donnée evt long
SELECT EME_C_CODE, EME_C_PRB, COUNT(1)
FROM C5.EME_LG_AVA_PRS
WHERE TRUNC(EME_D_CREATION) = '04/01/17'
GROUP BY EME_C_CODE, EME_C_PRB
ORDER BY 3 DESC
;

--Nb CE12 par date
SELECT TO_CHAR(EDI_D_CREATION, 'YYYY/MM/DD') as DATE_VOL, COUNT(1) as VOLUMETRIE
FROM C5.CE12
WHERE EDI_D_CREATION >=  '01/01/2017'
GROUP BY TO_CHAR(EDI_D_CREATION, 'YYYY/MM/DD')
ORDER BY 1
;

--Nb CE20 par date
SELECT TO_CHAR(EDI_D_CREATION, 'YYYY/MM/DD') as DATE_VOL, COUNT(1) as VOLUMETRIE
FROM C5.CE20
WHERE EDI_D_CREATION >=  '01/01/2017'
GROUP BY TO_CHAR(EDI_D_CREATION, 'YYYY/MM/DD')
ORDER BY 1
;

--Vol Indvt
SELECT COUNT(1), EME_T_INDEVT4, EME_T_INDEVT5 FROM C5.EME_LG_AVA_PRS lg
WHERE EME_C_CODE = 'PRS_REAL'
AND EME_C_PRB = 'PRB_MAJP'
AND TRUNC(EME_D_CREATION) = '04/01/17'
GROUP BY EME_T_INDEVT4, EME_T_INDEVT5
ORDER BY 1 DESC
;
