SELECT * FROM SUIVI.NATURE nat
WHERE NAT_C_TYPE = 'F140'
AND NAT_C_SOUS_TYPE = 'F140B1'
;

SELECT * FROM AFFAIRE.VARIABLE
WHERE VAR_C_CODE = 'B_MODIF_BRANCHEMENT'
;

--F120B1 avec auto-relevés
SELECT COUNT(1), B_AUTORELEVE_AR FROM
 (
  SELECT AFF_T_DISCO,
  MAX(CASE WHEN info.VAR_ID = 238679 THEN info.VAR_T_DATA END) as B_AUTORELEVE_AR
  FROM SUIVI.DEMANDE dem
  JOIN AFFAIRE.INFO_VARIABLE info ON info.AFF_ID = dem.DEM_ID 
  WHERE 1=1
  AND DEM_K_NAT = 8634
  AND info.VAR_ID =  238679
  AND DEM_D_DEMANDE > '01/01/2016'
  AND DEM_D_DEMANDE < '01/02/2016'
  GROUP BY AFF_T_DISCO
 )
GROUP BY B_AUTORELEVE_AR
;

--F120B1 avec modification des paramètres techniques
SELECT COUNT(1), B_PARAMETRE_TECHNIQUE_MODIFIE FROM
 (
  SELECT AFF_T_DISCO,
  MAX(CASE WHEN info.VAR_ID = 200131 THEN info.VAR_T_DATA END) as B_PARAMETRE_TECHNIQUE_MODIFIE
  FROM SUIVI.DEMANDE dem
  JOIN AFFAIRE.INFO_VARIABLE info ON info.AFF_ID = dem.DEM_ID 
  WHERE 1=1
  AND DEM_K_NAT = 8634
  AND info.VAR_ID =  200131
  AND DEM_D_DEMANDE > '01/01/2016'
  AND DEM_D_DEMANDE < '01/02/2016'
  GROUP BY AFF_T_DISCO
 )
GROUP BY B_PARAMETRE_TECHNIQUE_MODIFIE
;

--F120B1 avec modification des paramètres techniques (par média réception)
SELECT COUNT(1), B_PARAMETRE_TECHNIQUE_MODIFIE, R_MEDIA_RECEPTION FROM
 (
  SELECT AFF_T_DISCO,
  MAX(CASE WHEN info.VAR_ID = 200131 THEN info.VAR_T_DATA END) as B_PARAMETRE_TECHNIQUE_MODIFIE,
  MAX(CASE WHEN info.VAR_ID = 200068 THEN info.VAR_T_DATA END) as R_MEDIA_RECEPTION
  FROM SUIVI.DEMANDE dem
  JOIN AFFAIRE.INFO_VARIABLE info ON info.AFF_ID = dem.DEM_ID 
  WHERE 1=1
  AND DEM_K_NAT = 8634
  AND (info.VAR_ID =  200131 OR info.VAR_ID =  200068)
  AND DEM_D_DEMANDE > '01/01/2016'
  AND DEM_D_DEMANDE < '01/02/2016'
  GROUP BY AFF_T_DISCO
 )
GROUP BY B_PARAMETRE_TECHNIQUE_MODIFIE, R_MEDIA_RECEPTION
;
	--Résultat :
	15119	N	PORTAIL
	524	O	PORTAIL
	128815	N	B2B
	5353	O	B2B

--F120B1 avec index auto-relevés (par média réception)
SELECT COUNT(1), B_AUTORELEVE_AR FROM
 (
  SELECT AFF_T_DISCO,
  MAX(CASE WHEN info.VAR_ID = 238679 THEN info.VAR_T_DATA END) as B_AUTORELEVE_AR,
  MAX(CASE WHEN info.VAR_ID = 200068 THEN info.VAR_T_DATA END) as R_MEDIA_RECEPTION
  FROM SUIVI.DEMANDE dem
  JOIN AFFAIRE.INFO_VARIABLE info ON info.AFF_ID = dem.DEM_ID 
  WHERE 1=1
  AND DEM_K_NAT = 8634
  AND (info.VAR_ID =  238679 OR info.VAR_ID =  200068)
  AND DEM_D_DEMANDE > '01/01/2016'
  AND DEM_D_DEMANDE < '01/02/2016'
  GROUP BY AFF_T_DISCO
 )
GROUP BY B_AUTORELEVE_AR, R_MEDIA_RECEPTION
;
	--Résultat :
	131826	N	B2B
	2342	O	B2B
	13731	N	PORTAIL
	1912	O	PORTAIL
	
--F180B1 avec modification de branchement (par média réception)
SELECT COUNT(1), B_MODIF_BRANCHEMENT, R_MEDIA_RECEPTION FROM
 (
  SELECT AFF_T_DISCO,
  MAX(CASE WHEN info.VAR_ID = 200452 THEN info.VAR_T_DATA END) as B_MODIF_BRANCHEMENT,
  MAX(CASE WHEN info.VAR_ID = 200068 THEN info.VAR_T_DATA END) as R_MEDIA_RECEPTION
  FROM SUIVI.DEMANDE dem
  JOIN AFFAIRE.INFO_VARIABLE info ON info.AFF_ID = dem.DEM_ID 
  WHERE 1=1
  AND DEM_K_NAT = 8624
  AND (info.VAR_ID =  200452 OR info.VAR_ID =  200068)
  AND DEM_D_DEMANDE > '01/01/2016'
  AND DEM_D_DEMANDE < '01/02/2016'
  GROUP BY AFF_T_DISCO
 )
GROUP BY B_MODIF_BRANCHEMENT, R_MEDIA_RECEPTION
;
	--Résultat :
	7455	N	PORTAIL
	2467	O	PORTAIL
	30877	N	B2B
	2584	O	B2B

--F140B1 PORTAIL
SELECT COUNT(*) as RES FROM SUIVI.DEMANDE dem
JOIN SUIVI.NATURE nat on dem.DEM_K_NAT = nat.NAT_ID
JOIN SUIVI.ETAT_STATUT ee ON dem.DEM_K_EST_EXT = ee.EST_ID
WHERE 1=1
AND NAT_C_TYPE = 'F140'
AND NAT_C_SOUS_TYPE = 'F140B1'
AND DEM_R_STATUT = 'AFF-TERMINEE'
AND DEM_R_MEDIA_RECEPTION = 'PORTAIL'
AND DEM_D_DEMANDE > '01/01/16'
AND DEM_D_DEMANDE < '01/02/16'
;

--F180B1 avec modification de branchement sur situation potentielle
SELECT COUNT(1) FROM
 (
  SELECT AFF_T_DISCO,
  MAX(CASE WHEN info.VAR_ID = 200452 THEN info.VAR_T_DATA END) as B_MODIF_BRANCHEMENT,
  MAX(CASE WHEN info.VAR_ID = 218128 THEN info.VAR_T_DATA END) as R_PDL_SITUATION_DEMANDE
  FROM SUIVI.DEMANDE dem
  JOIN AFFAIRE.INFO_VARIABLE info ON info.AFF_ID = dem.DEM_ID 
  WHERE 1=1
  AND DEM_K_NAT = 8624
  AND (info.VAR_ID =  200452 OR info.VAR_ID =  218128)
  AND DEM_D_DEMANDE > '01/01/2016'
  AND DEM_D_DEMANDE < '01/02/2016'
  GROUP BY AFF_T_DISCO
 )
WHERE 1=1
--AND R_PDL_SITUATION_DEMANDE = 'P'
--AND B_MODIF_BRANCHEMENT = 'O'
;

--F30B2 v5.0 par FRN
SELECT COUNT(*) FROM (
  SELECT DISTINCT dem.AFF_T_DISCO,
  MAX(CASE WHEN info.VAR_ID = (
    SELECT VAR_ID FROM AFFAIRE.VARIABLE
    WHERE VAR_C_CODE = 'T_CME_VERSION'
  )
  THEN info.VAR_T_DATA END) as T_CME_VERSION
  FROM SUIVI.DEMANDE dem
  JOIN AFFAIRE.INFO_VARIABLE info ON info.AFF_ID = dem.DEM_ID
  JOIN SUIVI.FOURNISSEUR frn ON frn.FRN_ID = dem.DEM_K_FRN
  WHERE 1=1
  AND DEM_K_NAT = (
    SELECT NAT_ID FROM SUIVI.NATURE nat
    WHERE NAT_C_TYPE = 'F130B'
    AND NAT_C_SOUS_TYPE = 'F130B2'
  )
  AND info.VAR_ID IN (
    SELECT VAR_ID FROM AFFAIRE.VARIABLE
    WHERE VAR_C_CODE = 'T_CME_VERSION'
  )
  AND frn.FRN_C_ACTEUR = 'ACM_140'
  AND dem.DEM_D_DEMANDE > '04/06/2016'
  GROUP BY dem.AFF_T_DISCO
)
WHERE T_CME_VERSION = '5.0'
;

--Volumétrie par canal de demande
SELECT *
FROM SUIVI.DEMANDE dem
JOIN SUIVI.FOURNISSEUR frn ON frn.FRN_ID = dem.DEM_K_FRN
WHERE 1=1
--AND DEM_K_NAT IN (8643, 8635)
AND frn.FRN_C_ACTEUR = 'ACM_140'
AND dem.DEM_D_DEMANDE > '04/06/2016'
--AND DEM_D_DEMANDE < '04/05/2016'
AND DEM_R_MEDIA_RECEPTION = 'EAI'
ORDER BY 1 DESC
;

--Volumétrie M016 courante / potentielle
SELECT COUNT(*), R_PDL_SITUATION_DEMANDE FROM (
  SELECT DISTINCT dem.AFF_T_DISCO,
  MAX(CASE WHEN info.VAR_ID = (
    SELECT VAR_ID FROM AFFAIRE.VARIABLE
    WHERE VAR_C_CODE = 'R_PDL_SITUATION_DEMANDE'
  )
  THEN info.VAR_T_DATA END) as R_PDL_SITUATION_DEMANDE
  FROM SUIVI.DEMANDE dem
  JOIN AFFAIRE.INFO_VARIABLE info ON info.AFF_ID = dem.DEM_ID
  WHERE 1=1
  AND DEM_K_NAT IN (
    SELECT NAT_ID FROM SUIVI.NATURE nat
    WHERE NAT_C_TYPE IN ('F420C', 'F185', 'F360', 'F920', 'F940B')
  )
  AND info.VAR_ID IN (
    SELECT VAR_ID FROM AFFAIRE.VARIABLE
    WHERE VAR_C_CODE = 'R_PDL_SITUATION_DEMANDE'
  )
  AND dem.DEM_D_DEMANDE > '25/09/2016'
  GROUP BY dem.AFF_T_DISCO
)
GROUP BY R_PDL_SITUATION_DEMANDE
ORDER BY 1 DESC
;

--Volumétrie M016 retours DISCO
SELECT COUNT(*), K_RETOUR_DISB2B FROM (
  SELECT DISTINCT dem.AFF_T_DISCO,
  MAX(CASE WHEN info.VAR_ID = (
    SELECT VAR_ID FROM AFFAIRE.VARIABLE
    WHERE VAR_C_CODE = 'K_RETOUR_DISB2B'
  )
  THEN info.VAR_T_DATA END) as K_RETOUR_DISB2B
  FROM SUIVI.DEMANDE dem
  JOIN AFFAIRE.INFO_VARIABLE info ON info.AFF_ID = dem.DEM_ID
  WHERE 1=1
  AND DEM_K_NAT IN (
    SELECT NAT_ID FROM SUIVI.NATURE nat
    WHERE NAT_C_TYPE IN ('F420C', 'F185', 'F360', 'F920', 'F940B')
  )
  AND info.VAR_ID IN (
    SELECT VAR_ID FROM AFFAIRE.VARIABLE
    WHERE VAR_C_CODE = 'K_RETOUR_DISB2B'
  )
  AND dem.DEM_D_DEMANDE > '04/06/2016'
  GROUP BY dem.AFF_T_DISCO
)
WHERE 1=1
--AND K_RETOUR_DISB2B IN ('SGE4C1', 'SGE4C3')
GROUP BY K_RETOUR_DISB2B
ORDER BY 1 DESC
;

--Volumétrie M016 K_FOURNISSEUR_POTENTIEL_IDCOM
SELECT COUNT(*), K_FOURNISSEUR_POTENTIEL_IDCOM FROM (
  SELECT DISTINCT dem.AFF_T_DISCO,
  MAX(CASE WHEN info.VAR_ID = (
    SELECT VAR_ID FROM AFFAIRE.VARIABLE
    WHERE VAR_C_CODE = 'R_PDL_SITUATION_DEMANDE'
  ) THEN info.VAR_T_DATA END) as R_PDL_SITUATION_DEMANDE,
  MAX(CASE WHEN info.VAR_ID = (
    SELECT VAR_ID FROM AFFAIRE.VARIABLE
    WHERE VAR_C_CODE = 'K_FOURNISSEUR_POTENTIEL_IDCOM'
  ) THEN info.VAR_T_DATA END) as K_FOURNISSEUR_POTENTIEL_IDCOM
  FROM SUIVI.DEMANDE dem
  JOIN AFFAIRE.INFO_VARIABLE info ON info.AFF_ID = dem.DEM_ID
  WHERE 1=1
  AND DEM_K_NAT IN (
    SELECT NAT_ID FROM SUIVI.NATURE nat
    WHERE NAT_C_TYPE IN ('F420C', 'F185', 'F360', 'F920', 'F940B')
  )
  AND info.VAR_ID IN (
    SELECT VAR_ID FROM AFFAIRE.VARIABLE
    WHERE VAR_C_CODE IN ('R_PDL_SITUATION_DEMANDE', 'K_FOURNISSEUR_POTENTIEL_IDCOM')
  )
  AND dem.DEM_D_DEMANDE > '25/09/2016'
  GROUP BY dem.AFF_T_DISCO
)
WHERE 1=1
AND R_PDL_SITUATION_DEMANDE='C'
GROUP BY K_FOURNISSEUR_POTENTIEL_IDCOM
ORDER BY 1 DESC
;

--Volumétrie F200B cloturée avec et sans puissance de réduction
SELECT COUNT(1), MAX(AFF_T_DISCO) as EXEMPLE, NAT_C_SOUS_TYPE, R_INTERVENTION_REALISEE, R_TYPE_INTERVENTION FROM (
  SELECT aff.AFF_T_DISCO, natu.NAT_C_SOUS_TYPE,
  MAX(CASE WHEN var.VAR_C_CODE = 'R_INTERVENTION_REALISEE' THEN var.VAR_C_CODE ELSE 'NULL' END) as R_INTERVENTION_REALISEE,
  MAX(CASE WHEN var.VAR_C_CODE = 'R_TYPE_INTERVENTION' THEN var.VAR_C_CODE ELSE 'NULL' END) as R_TYPE_INTERVENTION
  FROM AFFAIRE.AFFAIRE aff
  LEFT JOIN AFFAIRE.INFO_VARIABLE inf ON aff.AFF_ID = inf.AFF_ID 
  LEFT JOIN AFFAIRE.VARIABLE var ON inf.VAR_ID = var.VAR_ID
  JOIN SUIVI.DEMANDE dema ON dema.AFF_T_DISCO = aff.AFF_T_DISCO
  JOIN SUIVI.NATURE natu ON dema.DEM_K_NAT = natu.NAT_ID
  WHERE aff.AFF_T_DISCO IN (
    SELECT dem.AFF_T_DISCO FROM SUIVI.DEMANDE dem
    JOIN SUIVI.NATURE nat on dem.DEM_K_NAT = nat.NAT_ID
    JOIN SUIVI.ETAT_STATUT ee ON dem.DEM_K_EST_EXT = ee.EST_ID
    JOIN SUIVI.FOURNISSEUR frn ON frn.FRN_ID = dem.DEM_K_FRN
    WHERE 1=1
    AND dem.DEM_B_IS_SGEL = 'N'
    AND nat.NAT_C_TYPE = 'F200B'
    AND nat.NAT_C_SOUS_TYPE IN ('F200B3', 'F200B4')
    AND frn.FRN_C_ACTEUR = 'ACM_140'
    AND dem.DEM_R_STATUT = 'AFF-TERMINEE'
    AND ee.EST_T_ETAT = 'Close, réduction de puissance'
    AND dem.DEM_D_DEMANDE > TO_DATE('01/09/16', 'DD/MM/YY')
  )
  --AND var.VAR_C_CODE = 'N_PUISSANCE_REDUCTION'
  GROUP BY aff.AFF_T_DISCO, natu.NAT_C_SOUS_TYPE
)
--WHERE NAT_C_SOUS_TYPE = 'F200B4' AND N_PUISSANCE_REDUCTION = 'NULL'
GROUP BY R_TYPE_INTERVENTION, R_INTERVENTION_REALISEE, NAT_C_SOUS_TYPE
ORDER BY 1 DESC
;
