--Désabonnements CdC
SELECT ETAT_CODE, COUNT(*) VOL FROM
(
	SELECT seg.PRM_ID POINT
	, srv.SERVICE_ID, srv.SERVICE_TYPE as TYPE_SERVICE, srv.PERIODICITE_TRANSMISSION
	, mes.TYPE_CODE as TYPE_MESURE, mes.PAS as PAS_MESURE, srv.ETAT_CODE
	, CASE  WHEN ben.TYPE = 'PERSONNE' THEN 'Client'
			WHEN ben.TYPE = 'FINALITE' THEN 'Interne'
			WHEN ben.TYPE = 'CONTRAT' AND (ben.code LIKE 'GRD-F%' or ben.code = 'PROTOC-501') THEN 'Fournisseur'
			WHEN ben.TYPE = 'CONTRAT' AND NOT (ben.code LIKE 'GRD-F%' or ben.code = 'PROTOC-501') THEN 'Tiers'
			ELSE 'Indéterminé'
			END "TYPE_DEMANDEUR"
	, CASE  WHEN ben.TYPE = 'FINALITE' THEN ben.CODE
			WHEN ben.TYPE = 'CONTRAT' THEN ben.LIBELLE
			END "DEMANDEUR"
	, TRUNC(srv.DATE_FIN) DATE_FIN
	FROM ADA_SCH.SERVICE_SOUSCRIT srv
	LEFT JOIN ADA_SCH.BENEFICIAIRE ben ON srv.BENEFICIAIRE_ID = ben.ID
	LEFT JOIN ADA_SCH.PRM_SEGMENT seg ON srv.PRM_SEGMENT_ID = seg.ID
	LEFT JOIN ADA_SCH.MESURE mes ON srv.MESURE_ID = mes.ID
	WHERE 1=1
	--AND srv.ETAT_CODE = 'TERMINE'
	AND seg.SEGMENT = 'C5'
	AND srv.SERVICE_TYPE IN ('TRANSREC')
	AND  mes.TYPE_CODE = 'CDC'
)
WHERE 1=1
AND DEMANDEUR = 'ENGIE'
AND DATE_FIN > TO_DATE('01/01/2020', 'dd/mm/yyyy')
AND DATE_FIN <= SYSDATE
GROUP BY ETAT_CODE
ORDER BY 2 DESC