SELECT sge.*
, rlv_gko.DATE_DER_RLV DATE_DER_RLV_GKO, rlv_gko.STATU_DER_RLV STATU_DER_RLV_GKO, rlv_gko.FACT_DER_RLV FACT_DER_RLV_GKO
FROM TGINKOSGE_DR_SI_7 sge
LEFT JOIN T_RLV_GINKO_20200911 rlv_gko ON sge.PRM = rlv_gko.PRM
WHERE 1=1
AND EN_SERVICE ='O'
AND TYPE_OFFRE ='OH'
AND DR = '@@DR@@'