SELECT sge.*
FROM SGE sge
LEFT JOIN RLV_GINKO rlv_g ON sge.PRM = rlv_g.PRM
LEFT JOIN RLV_DISCO rlv_d ON sge.PRM = rlv_d.IDPDLL
WHERE 1=1
AND SI NOT IN ('DISCO', 'GINKO')
AND EN_SERVICE ='O'
AND TYPE_OFFRE ='OH'