SELECT COMPTEUR, TYPE_CAL, COUNT(*) VOL FROM
(
	SELECT 
	CASE WHEN COMPTEUR = 'LINKY' AND CPT_COMMUNIQUANT = 'O' THEN 'LINKY COM'
		WHEN COMPTEUR = 'LINKY' AND CPT_COMMUNIQUANT = 'N' THEN 'LINKY NC'
		ELSE COMPTEUR END COMPTEUR
	, DECODE(CALENDRIER, 'FC000049', 'EJP', 'FC000050', 'TEMPO', 'AUTRE') TYPE_CAL
	FROM
	TGINKOSGE_DR_SI_7
	WHERE 1=1
	AND SI IN ('DISCO', 'GINKO')
	AND EN_SERVICE ='O'
	AND TYPE_OFFRE ='OH'
)
GROUP BY COMPTEUR, TYPE_CAL
ORDER BY 1
;