SELECT sge.PRM, sge.CODE_INSEE, sge.CODE_DEPARTEMENT, sge.CCD, sge.COMMUNE, sge.DR, sge.REG
, COALESCE(aff.SI, sge.SI) SI
, COALESCE(aff.EN_SERVICE, sge.EN_SERVICE) EN_SERVICE
, COALESCE(aff.TYPE_OFFRE, sge.TYPE_OFFRE) TYPE_OFFRE
, COALESCE(aff.CALENDRIER, sge.CALENDRIER) CALENDRIER
, COALESCE(aff.CAL_LIBELLE, sge.CAL_LIBELLE) CAL_LIBELLE
, COALESCE(aff.PS, sge.PS) PS
, sge.P_RAC
, COALESCE(aff.COMPTEUR, sge.COMPTEUR) COMPTEUR
, COALESCE(aff.CPT_COMMUNIQUANT, sge.CPT_COMMUNIQUANT) CPT_COMMUNIQUANT
, COALESCE(aff.CPT_ACCESSIBLE, sge.CPT_ACCESSIBLE) CPT_ACCESSIBLE
, COALESCE(aff.MODE_RLV, sge.MODE_RLV) MODE_RLV
, COALESCE(aff.MEDIA, sge.MEDIA) MEDIA
, sge.BP, sge.COLOC
, aff.AFFAIRE, aff.PRESTATION, aff.STATUT, aff.FOURNISSEUR ,aff.DATE_DEMANDE, aff.DATE_EFFET, aff.ISO
FROM TGINKOSGE_DR_SI_7 sge
JOIN DELTA_AFF_20200922 aff ON sge.PRM = aff.PRM
WHERE CODE_INSEE IS NOT NULL
AND sge.PRM = '17220694633131'