SELECT sge.*
FROM TGINKOSGE_DR_SI_7 sge
LEFT JOIN T_RLV_GINKO_20200911 rlv_g ON sge.PRM = rlv_g.PRM
LEFT JOIN T_RLV_DISCO_20200911 rlv_d ON sge.PRM = rlv_d.IDPDLL
WHERE 1=1
AND SI NOT IN ('DISCO', 'GINKO')
AND EN_SERVICE ='O'
AND TYPE_OFFRE ='OH'