SELECT TO_CHAR(dem.DEM_D_DEMANDE, 'YYYY/MM') as DATE_VOL
,COUNT(*) as VOL
, frn.FRN_T_ACTEUR as FOURNISSEUR
, dem.DEM_T_CLIENT as CLIENT
FROM SUIVI.DEMANDE dem
JOIN SUIVI.NATURE nat ON dem.DEM_K_NAT = nat.NAT_ID
LEFT JOIN SUIVI.ETAT_STATUT ee ON dem.DEM_K_EST_EXT = ee.EST_ID
JOIN SUIVI.ETAT_STATUT ei ON dem.DEM_K_EST_INT = ei.EST_ID
JOIN SUIVI.FOURNISSEUR frn ON frn.FRN_ID = dem.DEM_K_FRN
LEFT JOIN SUIVI.MAILLE mai ON mai.MAI_ID = dem.DEM_K_MAI
WHERE 1=1
AND DEM_C_WKF = 'M007-C2C4'
AND nat.NAT_C_PRESTATION IN ('M007')
AND dem.DEM_D_DEMANDE >= TO_DATE('01/09/2020', 'DD/MM/YYYY')
GROUP BY dem.DEM_T_CLIENT, frn.FRN_T_ACTEUR, TO_CHAR(dem.DEM_D_DEMANDE, 'YYYY/MM')
HAVING COUNT(*) > 10
ORDER BY 1 DESC