SELECT prm.PRM_ID AS POINT,
--compt.SCM_DC_STRUCTURE_COMPTAGE_CODE AS TYPE_DE_COMPTEUR,
compt.SCM_APP_APPLICATION_CODE AS TYPE_COMPTEUR,
--prm.PRM_SC_ETAT_CONTRACTUEL_CODE AS ETAT_PRM,
--prm.PRM_SC_SEGMENT AS PRM_SEGMENT,
situ.SCN_SIT_ETAT_CODE AS ETAT_CONTRACTUEL,
situ.SCN_SEGMENT AS SEGMENT_CONTRACT,
situ.SCN_CF_CATEGORIE_CODE AS CATEGORIE,
situ.SCN_ST_P_SOUSCRITE_MAX_V AS PUISSANCE_SOUSCRITES,
--situ.SCN_CF_TYPE_CONTRAT AS TYPE_CONTRAT,
situ.SCN_ETAT_CONTRACTUEL_CODE AS ETAT_SITUATION_CONTRAT,
situ.SCN_CF_NUMERO_CONTRAT AS FOURNISSEUR,
prm.PRM_DG_LIBELLE AS CONTRACTANT
FROM SGEL_PRM_SCH.T_PRM prm 
JOIN SGEL_PRM_SCH.T_SITUATION_COMPTAGE compt ON prm.SCM_ID = compt.SCM_ID
JOIN SGEL_PRM_SCH.T_SITUATION_CONTRACTUELLE situ ON situ.SCN_ID = prm.SCN_ID
WHERE 1=1
	AND compt.SCM_SITU_TYPE = 'C'
  AND prm.PRM_ID LIKE '@@PRM_RG_2@@%';