SELECT * FROM (		
	SELECT dem.AFF_T_DISCO as AFFAIRE, dem.DEM_ID_PRM as POINT	
	, dem.DEM_R_STATUT as STATUT, ee.EST_T_ETAT as ETAT_EXTERNE	
	, dem.DEM_D_DEMANDE as DATE_DEMANDE, dem.DEM_D_EFFET as DATE_EFFET	
	, jal.JAL_ETAT_EXTERNE JALON, jal.JAL_DATE_JALON DATE_JALON	
	, t_stru.STR_TAR_ST_FORTARACH FTA_AFF, t_stru.STR_TAR_ST_GFRN_CAL_CODE CAL_AFF, t_stru.STR_TAR_ST_PUISMAXVAL PS_AFF	
	, situ.SCN_ST_FORM_TARIF_ACHEMIN as FTA_PRM	
	, situ.SCN_GF_CALENDRIER_FOURN_CODE as CAL_PRM	
	, situ.SCN_ST_P_SOUSCRITE_MAX_V as PS_PRM	
	, DECODE(scm.SCM_DC_STRUCTURE_COMPTAGE_CODE,	
		'AMM', 'LINKY',
		scm.SCM_DC_STRUCTURE_COMPTAGE_CODE) as COMPTEUR
	, eqeDJ.EQE_DJ_INT_REGLAGE_V INT_DJ	
	, DENSE_RANK() OVER (PARTITION BY dem.AFF_T_DISCO ORDER BY jal.JAL_DATE_JALON DESC) RANG	
	FROM SUIVI.DEMANDE dem	
	JOIN SUIVI.NATURE nat ON dem.DEM_K_NAT = nat.NAT_ID	
	LEFT JOIN SUIVI.ETAT_STATUT ee ON dem.DEM_K_EST_EXT = ee.EST_ID	
	JOIN SUIVI.ETAT_STATUT ei ON dem.DEM_K_EST_INT = ei.EST_ID	
	JOIN SUIVI.FOURNISSEUR frn ON frn.FRN_ID = dem.DEM_K_FRN	
	LEFT JOIN SGEL_IAP_SCH.T_AFFAIRE aff ON dem.AFF_T_DISCO = aff.AFF_ID	
	LEFT JOIN SGEL_IAP_SCH.T_PRESTATION t_pres ON aff.AFF_ID_SEQUENCE = t_pres.AFF_ID_SEQUENCE	
	LEFT JOIN SGEL_IAP_SCH.T_STRUCTURE_TARIFAIRE t_stru ON t_pres.PRE_DEM_STR_TAR_ID = t_stru.STR_TAR_ID	
	LEFT JOIN SGEL_IAP_SCH.T_JALON jal ON (aff.AFF_ID_SEQUENCE = jal.AFF_ID_SEQUENCE)	
	LEFT JOIN SGEL_PRM_SCH.T_PRM prm ON dem.DEM_ID_PRM = prm.PRM_ID	
	LEFT JOIN SGEL_PRM_SCH.T_SITUATION_CONTRACTUELLE situ ON prm.SCN_ID = situ.SCN_ID	
	LEFT JOIN SGEL_PRM_SCH.T_SITUATION_COMPTAGE scm ON scm.SCM_ID = prm.SCM_ID	
	LEFT JOIN SGEL_PRM_SCH.T_EQUIPEMENT eqeDJ ON eqeDJ.EQE_ID = scm.EQE_DISJONCTEUR_ID	
	WHERE 1=1	
	AND nat.NAT_C_PRESTATION IN ('F130B')	
	AND frn.FRN_T_ACTEUR IN ('EDF Commerce')	
	AND dem.DEM_D_DEMANDE >= TO_DATE('09/11/2020', 'DD/MM/YYYY')	
--	AND TRUNC(dem.DEM_D_EFFET) = TO_DATE('14/01/2021', 'DD/MM/YYYY')	
	AND dem.DEM_T_REGROUPEMENT = 'RAFTOPT'	
	AND jal.JAL_ETAT_EXTERNE <> 'CLAA'	
	AND dem.AFF_T_DISCO IN ('A05CJLW5')	
)		
WHERE RANG = 1	