-- Liste des affaires F800 avec extraction données FRN
WITH bp AS (
	SELECT dem.AFF_T_DISCO AFFAIRE, dem.DEM_ID_PRM PRM, nat.NAT_C_PRESTATION as PRESTATION, dem.DEM_C_WKF WKF, dem.DEM_R_STATUT AFF_STATUT, es.EST_T_ETAT AFF_ETAT
	,(
		SELECT iv.var_t_data VALEUR_VARIABLE
		FROM affaire.affaire aff, affaire.info_variable iv, formulaire.variable fv
		WHERE iv.var_id = fv.var_id
		AND iv.aff_id = aff.aff_id
		AND aff.aff_t_disco = dem.aff_t_disco
		AND fv.var_c_code = 'R_TYPE_OFFRE'
	  ) AFF_TYPE_OFFRE
	, (
		SELECT iv.var_t_data VALEUR_VARIABLE
		FROM affaire.affaire aff, affaire.info_variable iv, formulaire.variable fv
		WHERE iv.var_id = fv.var_id
		AND iv.aff_id = aff.aff_id
		AND aff.aff_t_disco = dem.aff_t_disco
		AND fv.var_c_code = 'R_CONTRAT_REFERENCE'
	  ) AFF_CTR
	FROM SUIVI.DEMANDE dem
	JOIN SUIVI.ETAT_STATUT es ON dem.DEM_K_EST_INT = es.EST_ID
	JOIN SUIVI.NATURE nat ON dem.DEM_K_NAT = nat.NAT_ID
	WHERE 1=1
	AND nat.NAT_C_PRESTATION IN ('F800B')
	AND dem.DEM_C_WKF IN ('F800B-UH-C5','F800B-UH-C5-R01')
	AND dem.DEM_R_STATUT = 'AFF-ENCOURS'
)

, f130 AS (
	SELECT dem.AFF_T_DISCO as AFFAIRE, dem.DEM_ID_PRM as PRM
	, frn.FRN_T_ACTEUR as FRN_ENTRANT, acm.ACM_T_LIB FRN_SORTANT, dem.DEM_R_STATUT as STATUT, ee.EST_T_ETAT as ETAT_EXTERNE
	, dem.DEM_D_DEMANDE as DATE_DEMANDE, dem.DEM_D_EFFET as DATE_EFFET
	FROM SUIVI.DEMANDE dem
	JOIN SUIVI.NATURE nat ON dem.DEM_K_NAT = nat.NAT_ID
	LEFT JOIN SUIVI.ETAT_STATUT ee ON dem.DEM_K_EST_EXT = ee.EST_ID
	JOIN SUIVI.ETAT_STATUT ei ON dem.DEM_K_EST_INT = ei.EST_ID
	JOIN SUIVI.FOURNISSEUR frn ON frn.FRN_ID = dem.DEM_K_FRN
	LEFT JOIN SGEL_IAP_SCH.T_AFFAIRE aff ON dem.AFF_T_DISCO = aff.AFF_ID
	LEFT JOIN SGEL_IAP_SCH.T_PRESTATION t_pres ON (aff.AFF_ID_SEQUENCE = t_pres.AFF_ID_SEQUENCE AND PRE_RANG = '1')
	LEFT JOIN CONTRAT.ACTEUR_MARCHE acm ON t_pres.PRE_FOURNISSEUR_TITULAIRE_CTR = acm.ACM_C_CODE
	WHERE 1=1
	AND dem.DEM_B_IS_SGEL IN ('O')
	AND dem.DEM_B_IS_GINKO IN ('O')
	AND nat.NAT_C_PRESTATION IN ('F130B')
)

, p AS (
	SELECT prm.PRM_ID PRM, prm.PRM_SC_SEGMENT SEG
	, DECODE(situ.SCN_APP_APPLICATION_CODE, 'QETGC', 'DISCO', situ.SCN_APP_APPLICATION_CODE) as SI
	, prm.PRM_DG_APP_INSTANCE_SI INST_GKO, prm.PRM_DG_ETAT_CODE PRM_ETAT, prm.PRM_SC_ETAT_CONTRACTUEL_CODE ETAT_CTR
	, prm.PRM_DG_NUMERO_CONTRAT PRM_CTR
	, prm.PRM_DG_CENTRE_CODE CCD, prm.PRM_AI_CODE_INSEE CODE_INSEE, prm.PRM_AI_CODE_POSTAL CODE_POSTAL
	, prm.PRM_SC_DATE_PREMIERE_MES DATE_PREMIERE_MES, prm.PRM_SC_DATE_DER_MES DATE_DER_MES, prm.PRM_SC_DATE_DER_CHGT_FOURN DATE_DER_CHGT_FOURN
	, situ.SCN_NATURE_CODE SCN_NATURE
	FROM SGEL_PRM_SCH.T_PRM prm
	LEFT JOIN SGEL_PRM_SCH.T_SITUATION_CONTRACTUELLE situ ON prm.SCN_ID = situ.SCN_ID
)

SELECT * FROM
(
	SELECT 
	bp.AFFAIRE, bp.PRM, bp.PRESTATION, bp.WKF, bp.AFF_STATUT, bp.AFF_ETAT, bp.AFF_TYPE_OFFRE, bp.AFF_CTR
	, p.SI, p.INST_GKO, p.PRM_ETAT, p.ETAT_CTR, p.PRM_CTR, p.CCD, p.CODE_INSEE, p.CODE_POSTAL
	, p.DATE_PREMIERE_MES, p.DATE_DER_MES, p.DATE_DER_CHGT_FOURN
	, p.SCN_NATURE
	, CASE WHEN bp.AFF_CTR IN ('GRD-F003', 'PROTOC-501') AND p.PRM_CTR IN ('GRD-F003', 'PROTOC-501') THEN 'N'
		WHEN bp.AFF_CTR IS NULL AND bp.AFF_TYPE_OFFRE = 'OH_INTEGRE' AND p.PRM_CTR IN ('GRD-F003', 'PROTOC-501') THEN 'N'
		WHEN bp.AFF_CTR IS NULL AND bp.AFF_TYPE_OFFRE = 'OH_INTEGRE' AND p.PRM_CTR NOT IN ('GRD-F003', 'PROTOC-501') THEN 'O'
		WHEN bp.AFF_CTR <> p.PRM_CTR THEN 'O' ELSE 'N' END A_ANNULER
	, f130.AFFAIRE F130, f130.FRN_ENTRANT, f130.FRN_SORTANT, f130.STATUT STATU_F130, f130.ETAT_EXTERNE ETAT_F130
	, f130.DATE_DEMANDE D_DEM_F130, f130.DATE_EFFET D_EFFET_F130
	FROM bp
	LEFT JOIN p ON bp.PRM = p.PRM
	LEFT JOIN f130 ON bp.PRM = f130.PRM
	WHERE 1=1
	AND p.PRM_ETAT = 'ACTI'
	AND p.ETAT_CTR = 'SERVC'
	AND p.SI = 'GINKO'
)
WHERE 1=1
AND (A_ANNULER = 'O' OR F130 IS NOT NULL)
--AND AFF_TYPE_OFFRE = 'OH_INTEGRE'
AND AFFAIRE = 'A050B78G'