WITH t_disco as
(
	SELECT AFFAIRE, POINT, PRESTATION, OPT, CAT_CLIENT, FOURNISSEUR, STATUT, ETAT_EXTERNE
	, DATE_DEMANDE
	, MAX(CASE WHEN info.VAR_ID = (
			SELECT VAR_ID FROM AFFAIRE.VARIABLE
			WHERE VAR_C_CODE = 'D_RDV'
		) THEN info.VAR_T_DATA END) as DATE_PLANIFICATION
	, MEDIA, DR, REGION, SI, OUV_SRV, COMPTEUR
	FROM
	(
		SELECT DISTINCT dem.AFF_T_DISCO as AFFAIRE, dem.DEM_ID_PRM as POINT
		, nat.NAT_C_PRESTATION as PRESTATION
		, DECODE (nat.NAT_C_SOUS_TYPE
			, 'F200B1', 'Suspension'
			, 'F200B3', 'Suspension'
			, 'F200B4', 'Réduction'
			, 'F200BR', 'Rétablissement'
			, 'F200BRestaur', 'Restauration du limiteur de puissance') "OPT"
		, situ.SCN_CF_CATEGORIE_CODE as CAT_CLIENT
		, frn.FRN_T_ACTEUR as FOURNISSEUR
		, dem.DEM_R_STATUT as STATUT
		, ee.EST_T_ETAT as ETAT_EXTERNE
		, dem.DEM_D_DEMANDE as DATE_DEMANDE
		, dem.DEM_D_DEMANDE as DATE_PLANIFICATION
		, dem.DEM_R_MEDIA_RECEPTION as MEDIA
		, SUBSTR(mai.MAI_T_PLAQUE2, 6) DR, mai.MAI_T_REGION as REGION
		--, mai.MAI_T_TERRITOIRE as TERRITOIRE
		, 'DISCO' SI
		, prm.PRM_DG_NIV_OUV_SERV OUV_SRV
		, DECODE(scm.SCM_DC_STRUCTURE_COMPTAGE_CODE,
			'AMM', 'LINKY',
			scm.SCM_DC_STRUCTURE_COMPTAGE_CODE) as COMPTEUR
		, dem.DEM_ID
		FROM SUIVI.DEMANDE dem
		JOIN SUIVI.NATURE nat ON dem.DEM_K_NAT = nat.NAT_ID
		LEFT JOIN SUIVI.ETAT_STATUT ee ON dem.DEM_K_EST_EXT = ee.EST_ID
		JOIN SUIVI.ETAT_STATUT ei ON dem.DEM_K_EST_INT = ei.EST_ID
		JOIN SUIVI.FOURNISSEUR frn ON frn.FRN_ID = dem.DEM_K_FRN
		LEFT JOIN SUIVI.MAILLE mai ON mai.MAI_ID = dem.DEM_K_MAI
		JOIN SGEL_PRM_SCH.T_PRM prm ON prm.PRM_ID = dem.DEM_ID_PRM
		JOIN SGEL_PRM_SCH.T_SITUATION_CONTRACTUELLE situ ON prm.SCN_ID = situ.SCN_ID
		LEFT JOIN SGEL_PRM_SCH.T_SITUATION_COMPTAGE scm ON scm.SCM_ID = prm.SCM_ID
		WHERE 1=1
		AND dem.DEM_B_IS_SGEL IN ('N')
		AND dem.DEM_B_IS_GINKO IN ('N')
		AND nat.NAT_C_PRESTATION IN ('F200B')
	) a
	JOIN AFFAIRE.INFO_VARIABLE info ON info.AFF_ID = a.DEM_ID
	GROUP BY AFFAIRE, POINT, PRESTATION, OPT, CAT_CLIENT, FOURNISSEUR, STATUT, ETAT_EXTERNE, DATE_DEMANDE, MEDIA, DR, REGION, SI, OUV_SRV, COMPTEUR
)

, t_ginko as
(
	SELECT DISTINCT dem.AFF_T_DISCO as AFFAIRE, dem.DEM_ID_PRM as POINT
	, nat.NAT_C_PRESTATION as PRESTATION
	, DECODE(t_pres.PRE_DEM_OBJET_CODE
		, 'RET', 'Rétablissement'
		, 'SAI', 'Suspension'
		, 'RPI', 'Réduction'
		, 'RST', 'Restauration') AS "OPT"
	, situ.SCN_CF_CATEGORIE_CODE as CAT_CLIENT
	, frn.FRN_T_ACTEUR as FOURNISSEUR
	, dem.DEM_R_STATUT as STATUT
	, ee.EST_T_ETAT as ETAT_EXTERNE
	, dem.DEM_D_DEMANDE as DATE_DEMANDE
	, PLA_DATE as DATE_PLANIFICATION
	, dem.DEM_R_MEDIA_RECEPTION as MEDIA
	, SUBSTR(mai.MAI_T_PLAQUE2, 6) DR, mai.MAI_T_REGION as REGION
	--, mai.MAI_T_TERRITOIRE as TERRITOIRE
	, 'GINKO' SI
	, prm.PRM_DG_NIV_OUV_SERV OUV_SRV
	, DECODE(scm.SCM_DC_STRUCTURE_COMPTAGE_CODE,
		'AMM', 'LINKY',
		scm.SCM_DC_STRUCTURE_COMPTAGE_CODE) as COMPTEUR
	FROM SUIVI.DEMANDE dem
	JOIN SUIVI.NATURE nat ON dem.DEM_K_NAT = nat.NAT_ID
	LEFT JOIN SUIVI.ETAT_STATUT ee ON dem.DEM_K_EST_EXT = ee.EST_ID
	JOIN SUIVI.ETAT_STATUT ei ON dem.DEM_K_EST_INT = ei.EST_ID
	JOIN SUIVI.FOURNISSEUR frn ON frn.FRN_ID = dem.DEM_K_FRN
	LEFT JOIN SUIVI.MAILLE mai ON mai.MAI_ID = dem.DEM_K_MAI
	LEFT JOIN SGEL_IAP_SCH.T_AFFAIRE aff ON dem.AFF_T_DISCO = aff.AFF_ID
	LEFT JOIN SGEL_IAP_SCH.T_PRESTATION t_pres ON (aff.AFF_ID_SEQUENCE = t_pres.AFF_ID_SEQUENCE AND t_pres.PRE_RANG = '1')
	LEFT JOIN SGEL_IAP_SCH.T_INTERVENTION_AFFAIRE ia ON dem.AFF_T_DISCO = ia.AFF_ID
	LEFT JOIN SGEL_IAP_SCH.T_INTERVENTION t_inte ON ia.INT_ID = t_inte.INT_ID
	LEFT JOIN SGEL_IAP_SCH.T_PLANIFICATION t_plan ON t_inte.PLA_ID =  t_plan.PLA_ID
	JOIN SGEL_PRM_SCH.T_PRM prm ON prm.PRM_ID = dem.DEM_ID_PRM
	JOIN SGEL_PRM_SCH.T_SITUATION_CONTRACTUELLE situ ON prm.SCN_ID = situ.SCN_ID
	LEFT JOIN SGEL_PRM_SCH.T_SITUATION_COMPTAGE scm ON scm.SCM_ID = prm.SCM_ID
	WHERE 1=1
	AND dem.DEM_B_IS_SGEL IN ('O')
	AND dem.DEM_B_IS_GINKO IN ('O')
	AND nat.NAT_C_PRESTATION IN ('F200B')
	AND t_pres.PRE_DEM_OBJET_CODE IN ('RET', 'SAI', 'RPI', 'RST')
)

SELECT * FROM
(
	SELECT AFFAIRE, POINT, PRESTATION, OPT, CAT_CLIENT, FOURNISSEUR, STATUT, ETAT_EXTERNE, DATE_DEMANDE
	, TO_CHAR(TO_DATE(DATE_PLANIFICATION, 'DD/MM/YYYY'), 'DD/MM/YYYY') DATE_PLANIFICATION
	, MEDIA, DR, REGION, SI, OUV_SRV, COMPTEUR FROM t_disco
	UNION
	SELECT AFFAIRE, POINT, PRESTATION, OPT, CAT_CLIENT, FOURNISSEUR, STATUT, ETAT_EXTERNE, DATE_DEMANDE
	, TO_CHAR(DATE_PLANIFICATION, 'DD/MM/YYYY') DATE_PLANIFICATION
	, MEDIA, DR, REGION, SI, OUV_SRV, COMPTEUR FROM t_ginko
)
WHERE 1=1
--AND POINT = '01301881273008'
--AND AFFAIRE IN ('A054UU5Y', 'A054VX7K')
AND DATE_DEMANDE >= TO_DATE('04/08/2020', 'DD/MM/YYYY')
--AND DATE_DEMANDE <= TO_DATE('30/07/2020', 'DD/MM/YYYY')
AND FOURNISSEUR = 'EDF Commerce'
AND CAT_CLIENT = 'RES'