SELECT prm.PRM_ID, prm.PRM_SC_ETAT_CONTRACTUEL_CODE, situ.SCN_APP_APPLICATION_CODE, prm.PRM_DG_NUMERO_CONTRAT, situ.SCN_ST_TYPE_OFFRE_CODE
FROM SGEL_PRM_SCH.T_PRM prm
JOIN SGEL_PRM_SCH.T_SITUATION_CONTRACTUELLE situ ON prm.SCN_ID = situ.SCN_ID
WHERE 1=1
AND prm.PRM_SC_SEGMENT = 'C5'
AND prm.PRM_SC_ETAT_CONTRACTUEL_CODE = 'SERVC'
AND prm.PRM_DG_NUMERO_CONTRAT ='GRD-F003'
AND situ.SCN_ST_TYPE_OFFRE_CODE = 'OH'
AND prm.PRM_ID LIKE '@@PRM_RANGE_2@@%'
AND situ.SCN_APP_APPLICATION_CODE = 'GINKO'
;

SELECT COUNT(*) VOL, situ.SCN_APP_APPLICATION_CODE, prm.PRM_DG_NUMERO_CONTRAT, situ.SCN_CF_NUMERO_CONTRAT, situ.SCN_ST_TYPE_OFFRE_CODE
FROM SGEL_PRM_SCH.T_PRM prm
JOIN SGEL_PRM_SCH.T_SITUATION_CONTRACTUELLE situ ON prm.SCN_ID = situ.SCN_ID
WHERE 1=1
AND prm.PRM_SC_SEGMENT = 'C5'
AND prm.PRM_DG_NUMERO_CONTRAT IN ('PROTOC-501', 'GRD-F003')
AND prm.PRM_ID LIKE '@@PRM_RANGE_2@@%'
GROUP BY situ.SCN_APP_APPLICATION_CODE, prm.PRM_DG_NUMERO_CONTRAT, situ.SCN_CF_NUMERO_CONTRAT, situ.SCN_ST_TYPE_OFFRE_CODE
ORDER BY 1 DESC