--Affiche la liste des fournisseurs
SELECT DISTINCT acm.ACM_T_LIB "Acteur de marché", ctr.CTR_T_NUM "Contrat GRD", acm.ACM_C_CODE "Code SGE de l'acteur de marché", acta.ACT_C_EIC "Code EIC de l'acteur de marché", tam.TAM_C_CODE
FROM CONTRAT.ASS_CTR_TAM_ACM acta
JOIN CONTRAT.ACTEUR_MARCHE acm ON acm.ACM_ID = acta.ACM_ID
JOIN CONTRAT.TYPE_ACTEUR tam ON tam.TAM_ID = acta.TAM_ID
JOIN CONTRAT.CONTRAT ctr ON ctr.CTR_ID = acta.CTR_ID
WHERE 1=1
AND tam.TAM_C_CODE LIKE 'F%'
--AND ctr.CTR_T_NUM = 'PROTOC-501'
;

--Trouve des logins actifs par ACM_ID
SELECT DISTINCT uti.UTI_T_LOGIN FROM UTILISATEUR.UTILISATEUR uti
JOIN UTILISATEUR.ASS_PRF_UTI prf ON uti.UTI_ID = prf.UTI_ID
WHERE uti.ACM_ID = '38' --GDF : 27, EDF : 135, POWEO : 38
AND uti.UTI_B_ACTIF = 'O'
AND prf.APU_B_ACTIF = 'O'
ORDER BY uti.UTI_T_LOGIN ASC
;

--Liste prestas SGEL
SELECT DISTINCT NAT_C_TYPE as PRS, NAT_C_SOUS_TYPE as OPT
FROM SUIVI.DEMANDE dem
JOIN SUIVI.NATURE nat ON dem.DEM_K_NAT = nat.NAT_ID
WHERE DEM_B_IS_SGEL = 'O'
ORDER BY NAT_C_TYPE
;

--Codes retour DISCO
SELECT * FROM DISCO.CODE_RETOUR_DISCO_4_0 cr
JOIN DISCO.PROCESSUS_DISCO prc ON cr.PRD_ID = prc.PRD_ID
JOIN DISCO.MESSAGE_RETOUR_DISCO_4_0 mrd ON mrd.CRD_ID = cr.CRD_ID
JOIN DISCO.FAISABILITE fai ON fai.FAI_ID = mrd.FAI_ID
ORDER BY cr.CRD_C_CODE_DISCO
;

--T_REFERENTIEL
SELECT * FROM SGEL_TRV_SCH.T_REFERENTIEL
WHERE REF_CODE = 'DOUBL'
;

--Ajout d'un PDL dans la table de migration
DELETE FROM TECHNIQUE.PRM_MIGRANT_GINKO;
SELECT * FROM TECHNIQUE.PRM_MIGRANT_GINKO;
INSERT INTO TECHNIQUE.PRM_MIGRANT_GINKO (PRM_ID) VALUES ('19100578720647');

--Batchs SGEL
SELECT inst.JOB_NAME, batch.START_TIME, batch.END_TIME
FROM SGEL_BATCH_SCH.BATCH_JOB_EXECUTION batch
JOIN SGEL_BATCH_SCH.BATCH_JOB_INSTANCE inst ON inst.JOB_INSTANCE_ID = batch.JOB_INSTANCE_ID
WHERE JOB_NAME LIKE '%C15%'
ORDER BY batch.START_TIME DESC
;

--Calendriers et GPM
SELECT *
FROM SGEL_SCH.T_CALENDRIER cal
JOIN SGEL_SCH.T_STRUCTURE_TEMPORELLE sTemp ON sTemp.STT_Id = cal.STT_ID
--LEFT JOIN CONTRAT.CONTRAT ctr ON ctr.CTR_T_NUM = cal.CAL_CONTRAT_GRDF_ID
--LEFT JOIN CONTRAT.ASS_CTR_TAM_ACM acta ON ctr.CTR_ID = acta.CTR_ID
--LEFT JOIN CONTRAT.ACTEUR_MARCHE acm ON acm.ACM_ID = acta.ACM_ID
--LEFT JOIN SGEL_SCH.T_CLASSE_TEMPORELLE cTemp ON cTemp.CAL_ID = cal.CAL_ID
--LEFT JOIN SGEL_SCH.T_CALENDRIER_GPM cad_cal ON cad_cal.CAL_ID = cal.CAL_ID
--LEFT JOIN SGEL_SCH.T_GROUPE_PERIODE_MOBILE gpm ON gpm.GPM_ID = cad_cal.GPM_ID
WHERE 1=1
--AND sTemp.STT_DOM_TENS_AUT_CODE_1 = 'BTINF'
--AND cal.CAL_CODE_COPIE = 'FD000004'
--AND cal.CAL_LIBELLE = '6 cadrans'
--AND cal.CAL_LIBELLE_COMPTEUR = '     TEMPO      '
--AND cTemp.CTF_NUMERO_CADRAN = '4'
AND cal.CAL_CONTRAT_GRDF_ID = 'GRD-F006'
--AND acm.ACM_T_LIB LIKE 'ENGIE'
--AND cal.CAL_CATEGORIE = 'CAF'
--AND cal.CAL_CODE IN 'FP000281'
--AND STT_PROFILAGE_AUTORISE = '1'
ORDER BY cal.CAL_CODE
;


--CADTOCAL
SELECT * FROM SGEL_TRV_SCH.T_TRANSCODIFICATION
WHERE TRA_CODE = 'CADTOCAL'
ORDER BY 3
;