WITH hierarchie_geo AS (
	SELECT /*+ INLINE */ ID, ETATOBJET, RANG, TYPEDONNEEGEO, LIBELLE, NUMERO_COMPLEMENT, CODE_HIERARCHIE, MNEMONIQUE_HIERARCHIE, LIBELLE_HIERARCHIE, LIBELLEABREGE_HIERARCHIE, CODEINSEE_HIERARCHIE, MATRICULEVOIE_HIERARCHIE, RANG_HIERARCHIE, TYPEDONNEEGEO_HIERARCHIE, COMPLEMENTNUMERO_HIERARCHIE, TYPEDG_HIERARCHIE, CP_ID_HIERARCHIE, CP_HIERARCHIE, QUALITEDG_HIERARCHIE,
	length(hgeo.LIBELLE_HIERARCHIE) - length(replace(hgeo.LIBELLE_HIERARCHIE, '|', null)) AS no_niveau
	FROM gahfld.MV_BATCH_HIERARCHIE_DGEO hgeo
	WHERE rang = 6
)

SELECT DISTINCT
substr(replace(replace(hgeo.CODEINSEE_HIERARCHIE, '-', ''), 'VIDE', ''), 1, 5) AS "CODE_INSEE"
, SUBSTR(dt.LIBELLE, 20) AS DR
FROM GAHFLD.TESPACEDELIVRAISON edl
JOIN GAHFLD.TPOINTDESERVICE pds ON edl.ID = pds.ESPACEDELIVRAISON_ID
JOIN GAHFLD.EDL_DECOUPAGETERRITOIRE edldt ON edldt.SOURCE = edl.ID
JOIN GAHFLD.TDECOUPAGETERRITOIRE dt ON (dt.ID = edldt.DEST AND dt.TYPEDECOUPAGETERRITOIRE = '3')
LEFT JOIN hierarchie_geo hgeo ON edl.ADRESSE_ID = hgeo.id
WHERE pds.REFERENCE IN @@IN1@@