WITH inf as (
 SELECT dem.AFF_T_DISCO as AFFAIRE
 , MAX(CASE WHEN info.VAR_ID = (
  SELECT VAR_ID FROM AFFAIRE.VARIABLE
  WHERE VAR_C_CODE = 'T_COMMENTAIRE_ANNULATION_AFFAIRE'
 ) THEN info.VAR_T_DATA END) as T_COMMENTAIRE
 FROM SUIVI.DEMANDE dem
 JOIN AFFAIRE.INFO_VARIABLE info ON info.AFF_ID = dem.DEM_ID
 WHERE 1=1
 AND dem.DEM_B_IS_SGEL IN ('N')
 AND dem.DEM_B_IS_GINKO IN ('N')
 AND info.VAR_ID IN (SELECT VAR_ID FROM AFFAIRE.VARIABLE WHERE VAR_C_CODE IN ('T_COMMENTAIRE_ANNULATION_AFFAIRE'))
 GROUP BY dem.AFF_T_DISCO
)

, etp as (
 SELECT dem.AFF_T_DISCO AFFAIRE, tac.TAC_D_CREATION, tac.TAC_D_SORTIE
 , DENSE_RANK() OVER (PARTITION BY dem.AFF_T_DISCO ORDER BY tac.TAC_D_SORTIE, tac.TAC_D_CREATION DESC) RANG
 FROM SUIVI.DEMANDE dem
 LEFT JOIN AFFAIRE.TACHE tac ON tac.AFF_ID = dem.DEM_ID
 WHERE 1=1
)

SELECT DISTINCT dem.AFF_T_DISCO as AFFAIRE, DEM_ID_PRM POINT
, DECODE(dem.DEM_B_IS_GINKO, 'N', 'DISCO', 'O', 'GINKO') SI
, dem.DEM_R_STATUT as STA
, DECODE(DEM_K_MODALITE_RDV, '1', 'DIS', '2', 'FRN') MODALITE
, dem.DEM_R_MEDIA_RECEPTION as MEDIA, dem.DEM_D_DEMANDE as DATE_DEM, dem.DEM_D_EFFET as DATE_EFFET, dem.DEM_ID_PRM as PDL, nat.NAT_C_TYPE as PRS, nat.NAT_C_SOUS_TYPE as OPT, frn.FRN_T_ACTEUR as FRN, ee.EST_T_ETAT as EE, mai.MAI_T_REGION as REGION
, inf.T_COMMENTAIRE, etp.TAC_D_SORTIE DATE_DER_STATU
FROM SUIVI.DEMANDE dem
JOIN SUIVI.NATURE nat ON dem.DEM_K_NAT = nat.NAT_ID
JOIN SUIVI.ETAT_STATUT ee ON dem.DEM_K_EST_EXT = ee.EST_ID
JOIN SUIVI.FOURNISSEUR frn ON frn.FRN_ID = dem.DEM_K_FRN
JOIN SUIVI.MAILLE mai ON mai.MAI_ID = dem.DEM_K_MAI
LEFT JOIN inf ON dem.AFF_T_DISCO = inf.AFFAIRE
LEFT JOIN etp ON dem.AFF_T_DISCO = etp.AFFAIRE
WHERE 1=1
AND etp.RANG = 1
AND dem.AFF_T_DISCO IN @@IN1@@
