WITH t as(
	SELECT prm.PRM_ID as PRM
	, situ.SCN_GF_CALENDRIER_FOURN_CODE as CALENDRIER
	, situ.SCN_ST_FORM_TARIF_ACHEMIN as FTA
	, situ.SCN_ST_P_SOUSCRITE_MAX_V as PS
	FROM SGEL_PRM_SCH.T_PRM prm
	LEFT JOIN SGEL_PRM_SCH.T_SITUATION_CONTRACTUELLE situ ON prm.SCN_ID = situ.SCN_ID
	LEFT JOIN SGEL_SCH.T_CALENDRIER cal ON situ.SCN_GF_CALENDRIER_FOURN_CODE = cal.CAL_CODE
)

, aff as (
	SELECT dem.DEM_ID_PRM as PRM, dem.AFF_T_DISCO as AFFAIRE, nat.NAT_C_PRESTATION PRESTATION, dem.DEM_R_STATUT STATUT, dem.DEM_D_DEMANDE DATE_DEMANDE, dem.DEM_D_EFFET as DATE_EFFET, DECODE(dem.DEM_B_IS_GINKO, 'O', 'GINKO', 'N', 'DISCO') SI
	, frn.FRN_T_ACTEUR as FOURNISSEUR, ee.EST_T_ETAT as ETAT_EXTERNE
	, t_pres.PRE_DEM_SC_TYPEOFFRE TYPE_OFFRE, t_stru.STR_TAR_ST_FORTARACH FTA_CIBLE, t_stru.STR_TAR_ST_PUISMAXVAL PS_CIBLE, t_stru.STR_TAR_ST_GFRN_CAL_CODE CAL_CIBLE
	, DENSE_RANK() OVER (PARTITION BY dem.DEM_ID_PRM ORDER BY dem.DEM_D_DEMANDE DESC, t_stru.STR_TAR_ST_FORTARACH) as RANG
	FROM SUIVI.DEMANDE dem
	JOIN SUIVI.NATURE nat ON dem.DEM_K_NAT = nat.NAT_ID
	JOIN SUIVI.FOURNISSEUR frn ON frn.FRN_ID = dem.DEM_K_FRN
	LEFT JOIN SUIVI.ETAT_STATUT ee ON dem.DEM_K_EST_EXT = ee.EST_ID
	LEFT JOIN SGEL_IAP_SCH.T_AFFAIRE aff ON dem.AFF_T_DISCO = aff.AFF_ID
	LEFT JOIN SGEL_IAP_SCH.T_PRESTATION t_pres ON aff.AFF_ID_SEQUENCE = t_pres.AFF_ID_SEQUENCE
	LEFT JOIN SGEL_IAP_SCH.T_STRUCTURE_TARIFAIRE t_stru ON t_pres.PRE_DEM_STR_TAR_ID = t_stru.STR_TAR_ID
	WHERE 1=1
	AND nat.NAT_C_PRESTATION IN ('F120A', 'F120B', 'F130A', 'F130B', 'F140', 'F140A')
	AND dem.DEM_R_STATUT IN ('AFF-ENCOURS', 'AFF-TERMINEE')
	AND dem.DEM_D_EFFET >= TO_DATE('01/09/2020', 'DD/MM/YYYY')
)

, cal as (
	SELECT cal.CAL_CODE, cal.CAL_CODE_COPIE
	FROM SGEL_SCH.T_CALENDRIER cal
)

SELECT aff.PRM, aff.AFFAIRE, aff.SI, aff.PRESTATION, aff.STATUT, aff.ETAT_EXTERNE, aff.FOURNISSEUR, aff.TYPE_OFFRE, aff.DATE_DEMANDE, aff.DATE_EFFET
, CASE WHEN aff.STATUT = 'AFF-ENCOURS' AND aff.PRESTATION IN ('F130A', 'F130B') THEN t.PS ELSE NULL END PS_INIT
, CASE WHEN aff.STATUT = 'AFF-ENCOURS' AND aff.PRESTATION IN ('F130A', 'F130B') THEN aff.PS_CIBLE ELSE NULL END PS_CIBLE
, CASE WHEN aff.STATUT = 'AFF-ENCOURS' AND aff.PRESTATION IN ('F130A', 'F130B') THEN t.FTA ELSE NULL END FTA_INIT
, CASE WHEN aff.STATUT = 'AFF-ENCOURS' AND aff.PRESTATION IN ('F130A', 'F130B') THEN aff.FTA_CIBLE ELSE NULL END FTA_CIBLE
, CASE WHEN aff.STATUT = 'AFF-ENCOURS' AND aff.PRESTATION IN ('F130A', 'F130B') THEN t.CALENDRIER ELSE NULL END CAL_INIT
, CASE WHEN aff.STATUT = 'AFF-ENCOURS' AND aff.PRESTATION IN ('F130A', 'F130B') THEN aff.CAL_CIBLE ELSE NULL END CAL_CIBLE
, CASE WHEN aff.STATUT = 'AFF-ENCOURS' AND aff.PRESTATION IN ('F130A', 'F130B') THEN calc_init.CAL_CODE_COPIE ELSE NULL END CAL_COPIE_INIT
, CASE WHEN aff.STATUT = 'AFF-ENCOURS' AND aff.PRESTATION IN ('F130A', 'F130B') THEN calc_cible.CAL_CODE_COPIE ELSE NULL END CAL_COPIE_CIBLE
, CASE WHEN aff.STATUT = 'AFF-TERMINEE' OR aff.PRESTATION NOT IN ('F130A', 'F130B') OR aff.SI = 'DISCO' THEN NULL
		WHEN t.FTA = aff.FTA_CIBLE AND t.PS = aff.PS_CIBLE AND calc_init.CAL_CODE_COPIE = calc_cible.CAL_CODE_COPIE THEN 'O'
		ELSE 'N' END F130_EC_ISO
FROM aff
JOIN t ON aff.PRM = t.PRM
LEFT JOIN cal calc_init ON t.CALENDRIER = calc_init.CAL_CODE
LEFT JOIN cal calc_cible ON aff.CAL_CIBLE = calc_cible.CAL_CODE
WHERE 1=1
AND aff.RANG = 1
AND t.PRM IN @@IN1@@
-- AND t.PRM IN ('01273516633705', '01268162040512', '01270477513693', '01273371826499', '01404196735262')
