WITH aff_130 as (
	SELECT DISTINCT dem.DEM_ID_PRM as POINT, dem.AFF_T_DISCO as AFFAIRE, dem.DEM_D_EFFET as DATE_EFFET
	, DENSE_RANK() OVER (PARTITION BY dem.DEM_ID_PRM ORDER BY dem.DEM_D_DEMANDE DESC) as RANG
	FROM SUIVI.DEMANDE dem
	JOIN SUIVI.NATURE nat ON dem.DEM_K_NAT = nat.NAT_ID
	WHERE 1=1
	AND nat.NAT_C_PRESTATION IN ('F130B')
	AND dem.DEM_R_STATUT IN ('AFF-ENCOURS')
)

, aff_BP as (
	SELECT DISTINCT dem.DEM_ID_PRM as POINT, dem.AFF_T_DISCO as AFFAIRE
	, CASE WHEN nat.NAT_C_PRESTATION = 'F800B' THEN 'LONG' ELSE 'COURT' END TYPE
	, DENSE_RANK() OVER (PARTITION BY dem.DEM_ID_PRM ORDER BY dem.DEM_D_DEMANDE DESC) as RANG
	FROM SUIVI.DEMANDE dem
	JOIN SUIVI.NATURE nat ON dem.DEM_K_NAT = nat.NAT_ID
	WHERE 1=1
	AND nat.NAT_C_PRESTATION IN ('F800B', 'F820')
	AND dem.DEM_ID_PRM NOT LIKE '00%'
	AND dem.DEM_R_STATUT <> 'AFF-ANNULEE'
)

SELECT DISTINCT PRM, SEG, CODE_INSEE, CODE_DEPARTEMENT, t.CCD, COMMUNE
, SI, EN_SERVICE, CONTRAT
, CASE WHEN TYPE_OFFRE_SCN IS NULL THEN TYPE_OFFRE_CTR ELSE TYPE_OFFRE_SCN END TYPE_OFFRE
, CALENDRIER, CAL_LIBELLE, FTA
, PS, P_RAC
, COMPTEUR, NIV_OUV_SERV, CPT_COMMUNICANT, CPT_TELEOPERABLE, CPT_ACCESSIBLE, MODE_RLV, MEDIA
, INT_REGLAGE_DJ, CALIBRE_DJ, PARTICULARITE
, BP
, COLOC
, F130_EC, DATE_EFFET
FROM
(
	SELECT prm.PRM_ID as PRM
	, prm.PRM_SC_SEGMENT SEG
	, DECODE(situ.SCN_APP_APPLICATION_CODE, 'QETGC', 'DISCO', situ.SCN_APP_APPLICATION_CODE) as SI
	, prm.PRM_SC_ETAT_CONTRACTUEL_CODE ETAT_CONTRACTUEL
	, CASE WHEN prm.PRM_SC_ETAT_CONTRACTUEL_CODE = 'SERVC' THEN 'O' ELSE 'N' END EN_SERVICE
	, CASE WHEN situ.SCN_ST_TYPE_OFFRE_CODE = 'OH' AND situ.SCN_APP_APPLICATION_CODE = 'QETGC' THEN 'PROTOC-501' ELSE prm.PRM_DG_NUMERO_CONTRAT END CONTRAT
	, situ.SCN_ST_TYPE_OFFRE_CODE TYPE_OFFRE_SCN
	, CASE WHEN prm.PRM_DG_NUMERO_CONTRAT = 'PROTOC-501' THEN 'OH' ELSE 'NO' END as TYPE_OFFRE_CTR
	, situ.SCN_GF_CALENDRIER_FOURN_CODE as CALENDRIER
	, situ.SCN_ST_FORM_TARIF_ACHEMIN as FTA
	, situ.SCN_ST_P_SOUSCRITE_MAX_V as PS
	, talim.ALI_PUISS_RACCO_SOUTI_V as P_RAC
	, cal.CAL_LIBELLE_COMPTEUR CAL_LIBELLE
	, DECODE(scm.SCM_DC_STRUCTURE_COMPTAGE_CODE,'AMM', 'LINKY','', 'SSCPT',scm.SCM_DC_STRUCTURE_COMPTAGE_CODE) as COMPTEUR
	, scm.SCM_MODE_RELEVE_CODE MODE_RLV
	, scm.SCM_MEDIA_CODE MEDIA
	, prm.PRM_DG_NIV_OUV_SERV NIV_OUV_SERV
	, CASE WHEN prm.PRM_DG_NIV_OUV_SERV > 0 THEN 'O'
			WHEN scm.SCM_MODE_RELEVE_CODE = 'TRLV' THEN 'O'
			ELSE 'N' END CPT_COMMUNICANT
	, CASE WHEN situ.SCN_APP_APPLICATION_CODE IN ('QETGC', 'GINKO') THEN CASE WHEN scm.SCM_TELEOPERABLE = '1' THEN 'O' ELSE 'N' END
			ELSE NULL END CPT_TELEOPERABLE
	, eqeDJ.EQE_DJ_INT_REGLAGE_V INT_REGLAGE_DJ, eqeDJ.EQE_DJ_CALIBRE_CODE CALIBRE_DJ
	, DECODE(eqeCPT.EQE_ACCESSIBILITE, '0', 'N', '1', 'O', 'N') CPT_ACCESSIBLE
	, scm.SCM_DC_PARTICULARITE_CODE PARTICULARITE
	, prm.PRM_AI_CODE_INSEE CODE_INSEE
	, CASE WHEN SUBSTR(prm.PRM_ID, 1, 3) LIKE '500%' OR SUBSTR(prm.PRM_ID, 1, 3) LIKE '300%'
		THEN prm.PRM_DG_CENTRE_CODE ELSE SUBSTR(prm.PRM_ID, 1, 3)
		END CCD
	, SUBSTR(prm.PRM_AI_CODE_INSEE, 1, 2) CODE_DEPARTEMENT
	, SUBSTR(prm.PRM_AIN_LIGNE6, 7) COMMUNE
	, aff_BP.TYPE as BP
	, CASE WHEN cf.PRS_MOR_ACTIVITE = 'COLOC' THEN 'O' ELSE 'N' END COLOC
	, aff_130.AFFAIRE F130_EC, aff_130.DATE_EFFET
	FROM SGEL_PRM_SCH.T_PRM prm
	LEFT JOIN SGEL_PRM_SCH.T_SITUATION_CONTRACTUELLE situ ON prm.SCN_ID = situ.SCN_ID
	LEFT JOIN SGEL_SCH.T_CALENDRIER cal ON situ.SCN_GF_CALENDRIER_FOURN_CODE = cal.CAL_CODE
	LEFT JOIN SGEL_PRM_SCH.T_SITUATION_COMPTAGE scm ON scm.SCM_ID = prm.SCM_ID
	LEFT JOIN SGEL_PRM_SCH.T_EQUIPEMENT eqeCPT ON eqeCPT.SCM_C_ID = prm.SCM_ID
	LEFT JOIN SGEL_PRM_SCH.T_EQUIPEMENT eqeDJ ON eqeDJ.EQE_ID = scm.EQE_DISJONCTEUR_ID
	LEFT JOIN SGEL_PRM_SCH.T_SITUATION_ALIMENTATION alim ON prm.SAL_ID = alim.SAL_ID
	LEFT JOIN SGEL_PRM_SCH.T_ALIMENTATION talim ON talim.ALI_ID = alim.ALI_PRINCIPALE_ID
	LEFT JOIN SGEL_PRM_SCH.T_PERSONNE cf ON situ.SCN_CLIENT_FINAL_ID = cf.PRS_ID
	LEFT JOIN aff_130 aff_130 ON (prm.PRM_ID = aff_130.POINT AND aff_130.RANG = 1)
	LEFT JOIN aff_BP aff_BP ON (prm.PRM_ID = aff_BP.POINT AND aff_BP.RANG = 1)
	WHERE 1=1
--	AND prm.PRM_ID IN @@IN1@@
	AND prm.PRM_ID IN ('09620984080770', '22177279218565', '25675976808201', '02444862487788', '30000731502759', '19524167854286', '01100144557179', '01100289273089', '30000110326267', '30000751220199', '30002130773580', '01181186604919')
	-- AND prm.PRM_ID = '22177279218565'
	--AND prm.PRM_TECH_DATE_MAJ >= TO_DATE('13/09/2020', 'DD/MM/YYYY')
) t