WITH t as(
	SELECT prm.PRM_ID as POINT
	, DECODE(situ.SCN_APP_APPLICATION_CODE
		, 'QETGC', 'DISCO'
		, situ.SCN_APP_APPLICATION_CODE) as SI
	, CASE WHEN prm.PRM_SC_ETAT_CONTRACTUEL_CODE = 'SERVC' THEN 'O' ELSE 'N' END EN_SERVICE
	
	, CASE WHEN situ.SCN_ST_TYPE_OFFRE_CODE IS NULL THEN
			CASE WHEN prm.PRM_DG_NUMERO_CONTRAT = 'PROTOC-501' THEN 'OH' ELSE 'NO' END
		ELSE situ.SCN_ST_TYPE_OFFRE_CODE
		END TYPE_OFFRE
	, situ.SCN_GF_CALENDRIER_FOURN_CODE as CALENDRIER
	, situ.SCN_ST_FORM_TARIF_ACHEMIN as FTA
	, situ.SCN_ST_P_SOUSCRITE_MAX_V as PS
	, DECODE(scm.SCM_DC_STRUCTURE_COMPTAGE_CODE,
		'AMM', 'LINKY',
		'', 'SSCPT'
		,scm.SCM_DC_STRUCTURE_COMPTAGE_CODE
		) as COMPTEUR
	, scm.SCM_MODE_RELEVE_CODE MODE_RLV
	, scm.SCM_MEDIA_CODE MEDIA
	, CASE WHEN prm.PRM_DG_NIV_OUV_SERV > 0 THEN 'O'
			WHEN scm.SCM_MODE_RELEVE_CODE = 'TRLV' THEN 'O'
			ELSE 'N' END CPT_COMMUNIQUANT
		, DECODE(eqeCPT.EQE_ACCESSIBILITE
		, '0', 'N'
		, '1', 'O'
		, 'N'
		) CPT_ACCESSIBLE
	FROM SGEL_PRM_SCH.T_PRM prm
	LEFT JOIN SGEL_PRM_SCH.T_SITUATION_CONTRACTUELLE situ ON prm.SCN_ID = situ.SCN_ID
	LEFT JOIN SGEL_SCH.T_CALENDRIER cal ON situ.SCN_GF_CALENDRIER_FOURN_CODE = cal.CAL_CODE
	LEFT JOIN SGEL_PRM_SCH.T_SITUATION_COMPTAGE scm ON scm.SCM_ID = prm.SCM_ID
	LEFT JOIN SGEL_PRM_SCH.T_EQUIPEMENT eqeCPT ON eqeCPT.SCM_C_ID = prm.SCM_ID
	WHERE 1=1
	--AND prm.PRM_ID IN ('02444862487788', '19524167854286', '01100144557179', '01100289273089', '30000110326267', '30000751220199', '30002130773580')
)

, aff as (
	SELECT dem.DEM_ID_PRM as POINT, dem.AFF_T_DISCO as AFFAIRE, nat.NAT_C_PRESTATION PRESTATION, dem.DEM_R_STATUT STATUT, frn.FRN_T_ACTEUR as FOURNISSEUR
	, dem.DEM_D_DEMANDE DATE_DEMANDE, dem.DEM_D_EFFET as DATE_EFFET
	, t_stru.STR_TAR_ST_FORTARACH FTA_CIBLE, t_stru.STR_TAR_ST_PUISMAXVAL PS_CIBLE, t_stru.STR_TAR_ST_GFRN_CAL_CODE CAL_CIBLE
	, DENSE_RANK() OVER (PARTITION BY dem.DEM_ID_PRM ORDER BY dem.DEM_D_DEMANDE DESC, t_stru.STR_TAR_ST_FORTARACH) as RANG
	FROM SUIVI.DEMANDE dem
	JOIN SUIVI.NATURE nat ON dem.DEM_K_NAT = nat.NAT_ID
	JOIN SUIVI.FOURNISSEUR frn ON frn.FRN_ID = dem.DEM_K_FRN
	LEFT JOIN SGEL_IAP_SCH.T_AFFAIRE aff ON dem.AFF_T_DISCO = aff.AFF_ID
	LEFT JOIN SGEL_IAP_SCH.T_PRESTATION t_pres ON aff.AFF_ID_SEQUENCE = t_pres.AFF_ID_SEQUENCE
	LEFT JOIN SGEL_IAP_SCH.T_STRUCTURE_TARIFAIRE t_stru ON t_pres.PRE_DEM_STR_TAR_ID = t_stru.STR_TAR_ID
	WHERE 1=1
	AND nat.NAT_C_PRESTATION IN ('F120B', 'F130B', 'F140', 'F180')
	AND (
		dem.DEM_R_STATUT = 'AFF-ENCOURS'
		OR
		(dem.DEM_R_STATUT = 'AFF-TERMINEE' AND dem.DEM_D_DEMANDE >= TO_DATE('03/09/2020', 'DD/MM/YYYY')) -->= SYSDATE - 7
		)
)

, cal as (
	SELECT CAL_CODE, COUNT(*) NB_CT
	FROM SGEL_SCH.T_CALENDRIER cal
	LEFT JOIN SGEL_SCH.T_CLASSE_TEMPORELLE cTemp ON cTemp.CAL_ID = cal.CAL_ID
	WHERE 1=1
	GROUP BY cal.CAL_CODE
)

SELECT t.POINT
, t.SI, t.EN_SERVICE, t.TYPE_OFFRE, t.CALENDRIER, t.COMPTEUR, t.MODE_RLV, t.MEDIA, t.CPT_COMMUNIQUANT, t.CPT_ACCESSIBLE
, aff.AFFAIRE, aff.PRESTATION, aff.STATUT, aff.FOURNISSEUR ,aff.DATE_DEMANDE, aff.DATE_EFFET
-- , t.FTA FTA_INIT, aff.FTA_CIBLE
-- , t.PS PS_INIT, aff.PS_CIBLE
-- , t.CALENDRIER CAL_INIT, aff.CAL_CIBLE
-- , cal_init.NB_CT NB_CT_INIT, cal_cible.NB_CT NB_CT_CIBLE
-- , CASE WHEN aff.STATUT = 'AFF-TERMINEE' THEN ''
		-- WHEN t.FTA = aff.FTA_CIBLE AND t.PS = aff.PS_CIBLE AND cal_init.NB_CT = cal_cible.NB_CT THEN 'O'
		-- ELSE 'N' END ISO
FROM aff
JOIN t t ON aff.POINT = t.POINT
LEFT JOIN cal cal_init ON t.CALENDRIER = cal_init.CAL_CODE
LEFT JOIN cal cal_cible ON aff.CAL_CIBLE = cal_cible.CAL_CODE
WHERE 1=1
AND aff.RANG = 1
AND t.POINT IN @@IN1@@