--Conversion colonne en format nombre
INSERT INTO TEST2 (
	SELECT "PRM", "SEG", "CODE_INSEE", "CODE_DEPARTEMENT", "CCD", "COMMUNE", "SI", "ETAT_CONTRACTUEL", "EN_SERVICE", "CONTRAT", "TYPE_OFFRE", "CALENDRIER", "CAL_LIBELLE", "FTA"
	, "PS", "P_RAC"
	, REPLACE(PS,'.',',') PS_NUM
	, REPLACE(P_RAC,'.',',') P_RAC_NUM
	, "COMPTEUR", "NIV_OUV_SERV", "CPT_COMMUNICANT", "CPT_TELEOPERABLE", "CPT_ACCESSIBLE", "MODE_RLV", "MEDIA", "INT_REGLAGE_DJ", "CALIBRE_DJ", "PARTICULARITE", "BP", "COLOC", "F130_EC", "DATE_EFFET"
	FROM SGE
--	WHERE ROWNUM < 100
--	AND PS IS NOT NULL
);